openapi: 3.0.0
info:
  version: 1.0.0
  title: Generic Service 
  description: Common Service
paths:
  /common-service/v1/_init:
    post:
      tags:
        - Generic Service
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ServiceInitRequest'
      responses:
        '202':
          description: Accepted account registration request.
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ServiceInitResponse'
        '400':
          description: Invalid input.
          content:
            '*/*':
              schema:
                $ref: >-
                  https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/ErrorRes
  /common-service/v1/_apply:
    post:
      tags:
        - Application Service
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ApplicationRequest'
      responses:
        '202':
          description: Accepted account registration request.
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ApplicationResponse'
        '400':
          description: Invalid input.
          content:
            '*/*':
              schema:
                $ref: >-
                  https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/ErrorRes
  /common-service/v1/_update:
    post:
      tags:
        - Application Service
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ApplicationRequest'
      responses:
        '202':
          description: Accepted account updation request.
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ApplicationResponse'
        '400':
          description: Invalid input.
          content:
            '*/*':
              schema:
                $ref: >-
                  https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/ErrorRes
  /common-service/v1/_search:
    post:
      tags:
        - Application Service
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ApplicationSearchRequest'
      responses:
        '200':
          description: Return search results
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ApplicationResponse'
        '400':
          description: Invalid input.
          content:
            '*/*':
              schema:
                $ref: >-
                  https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/ErrorRes


components:
  schemas:
    Application:
      description: A Object which holds the info about the application details
      type: object
      properties:
        id:
          description: Unique identifier of the record
          readOnly: true
          type: string
          minLength: 2
          maxLength: 64
          example: "8801de85-f123-4e4b-9e4e-adbd04e49965"
        tenantId:
          description: Tenant Identifier
          example: pg
          type: string
          minLength: 2
          maxLength: 64
        service:
          type: string
          description: all the enabled service like tradelicence / propertytax etc
          minLength: 2
          maxLength: 64
          example: tradelicence
        businessService:
          description: captures the businessService information to be used in workflow service like NEWTL / RENEWTL NEWPROPERTY etc
          example: NEWTL
          type: string
          minLength: 2
          maxLength: 64
        
        applicationNo:
          maxLength: 64
          minLength: 2
          type: string
          description: Unique Application Number. This is  unique in
            system for a tenant. This is mandatory but always be generated after validation.
          readOnly: true
        status:
          $ref: '#/components/schemas/Status'
        channel:
          description: channel which this application created like citizen/ employee/ system
          example: citizen
          type: string
          minLength: 2
          maxLength: 64  
        references:
          type: array
          items:
            $ref: '#/components/schemas/Reference'

        workflowStatus:
          type: string
          minLength: 2
          maxLength: 64
          description: applied / approved according to workflow config
          example: applied
        serviceDetails:
          description: Service related information
          type: object
        applicants:
          type: array
          items:
            $ref: '#/components/schemas/Applicant'
        address:
          $ref: https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract.yml#/definitions/Address
        additionalDetails:
          description: Any additional details that need to be captured
          type: object
        auditDetails:
          $ref: https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract.yml#/definitions/AuditDetails
      required:
        - tenantId
        - businessService
        - serviceDetails
        - service

    ServiceInitRequest:
      type: object
      properties:
        RequestInfo:
          $ref: >-
                https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/RequestInfo
        Service:
          $ref: '#/components/schemas/Service'
          
    ServiceInitResponse:
      type: object
      properties:
        ResponseInfo:
          $ref: >-
                https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/ResponseInfo
        Services:
          type: array
          items:
            $ref: '#/components/schemas/Service'
        pagination:
          $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-OSS/367d45e50eb274ccaabeddc302bc34420edebe09/core-services/docs/common-contract_v1-1.yml#/components/schemas/Pagination'

    Service:
      description: A Object which holds the info about the application details
      type: object
      properties:
        id:
          description: Unique identifier of the Service Registered
          readOnly: true
          type: string
          minLength: 2
          maxLength: 64
          example: "8801de85-f123-4e4b-9e4e-adbd04e49965"
        tenantId:
          description: Tenant Identifier
          example: pg
          type: string
          minLength: 2
          maxLength: 64
        serviceType:
          type: string
          description: all the enabled service like tradelicence / propertytax etc
          minLength: 2
          maxLength: 64
          example: newTL
        module:
          type: string
          description: all the enabled service like tradelicence / propertytax etc
          minLength: 2
          maxLength: 64
          example: tradelicence
        status:
          description: enum value for the payment status 
          type: string
          enum: [INACTIVE, ACTIVE]
        additionalDetails:
          description: Any additional details that need to be captured
          type: object
        auditDetails:
          $ref: https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract.yml#/definitions/AuditDetails
      required:
        - tenantId
        - module
        - serviceType

    ApplicationRequest:
      type: object
      properties:
        RequestInfo:
          $ref: >-
                https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/RequestInfo
        Application:
          $ref: '#/components/schemas/Application'
        Workflow:
          $ref: >-
                https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/Workflow
    ApplicationResponse:
      type: object
      properties:
        ResponseInfo:
          $ref: >-
                https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/ResponseInfo
        Applications:
          type: array
          items:
            $ref: '#/components/schemas/Application'
        pagination:
          $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-OSS/367d45e50eb274ccaabeddc302bc34420edebe09/core-services/docs/common-contract_v1-1.yml#/components/schemas/Pagination'
    ApplicationCriteria:
      type: object
      properties:
        tenantId:
          description: Tenant Identifier
          example: pg.citya
          type: string
          minLength: 2
          maxLength: 64
        ids:
          type: array
          description: Search by bill ids 
          items:
            type: string
            example: 'c453edf5-0b89-4040-8f34-b8fbdfac1b2e'
        businessService:
          description: Search bill by business service
          example: WORKS-MUSTERROLE
          type: string
          minLength: 2
          maxLength: 64
        referenceId:
          description: search bill by  referance ids         
          type: array
          items:
            type: string
        status:
          $ref: '#/components/schemas/Status'
      required: 
        - tenantId
    ApplicationSearchRequest:
      type: object
      properties:
        RequestInfo:
          $ref: >-
                https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/RequestInfo
        searchCriteria:
          $ref: '#/components/schemas/ApplicationCriteria'
        pagination:
          $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/Pagination'
    Status:
      description: enum value for the payment status 
      type: string
      enum: [INACTIVE, ACTIVE, INWORKFLOW]


    Reference:
      type: object
      properties:
        referenceId:
          description: reference id to current entity
          type: string
          minLength: 2
          maxLength: 64
          example: 8801de85-f123-4e4b-9e4e-adbd04e49965
        referenceType:
          description: Pass reference type in the service to uniquely identify 
          type: string
          minLength: 2
          maxLength: 64
          example: propertytax
        service:
          description: Pass reference service information like billing / payment / internal
          type: string
          minLength: 2
          maxLength: 64
          example: internal
        tenantId:
          description: Tenant Identifier
          example: pg
          type: string
          minLength: 2
          maxLength: 64
        referenceNo:
          description: Tenant Identifier
          example: pg
          type: string
          minLength: 2
          maxLength: 64
      required: 
      - referenceId
      - service
    Applicant:
      type: object
      properties:
        type:
          description: allowed usertype
          type: string
          minLength: 2
          maxLength: 64
          example: citizen inidvidual institution
        name:
          description: name of the user
          type: string
          minLength: 2
          maxLength: 64
          example: John

        mobileNumber:
          type: integer
          description: Mobile number of the user
          example: 99999999999
        emailId:
          description: name of the user
          type: string
          maxLength: 64
          example: john@gmail.com  

        prefix:
          type: string
          description: country prefix
          example: +91
