openapi: 3.0.0
info:
  version: "1.0.0"
  title: eGov Noc(No objection certificate) application registry
  description: |
    Noc registry store and serve the NOC related information using rest APIs
    Mainly it has below functionalities
    1. Apply for new NOC
    2. Allow user to search the existing NOC information based on roles
    3. Allow user to take action on the application based on the user role
    4. Update the NOC information for an existing application based state and role configuration
    
  contact:
    name: Egovernments Foundation
    email: contact@egovernments.org
x-module: NOC
x-common-path: 'https://raw.githubusercontent.com/egovernments/egov-services/PT_APPLY_PAY/docs/common/contracts/v1-1-1.yml'
paths:
  
  /v1/noc/_create:
    post:
      tags:
        - Noc Apply
      summary: Apply for an NOC.
      description: Citizen or Employee, can apply for new build plan approval
      operationId: createUsingPOST
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NocRequest'
      
      
      responses:
        '200':
          description: OK
        '202':
          description: Application submitted successfully
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/NocResponse'
        '201':
          description: Created
        '400':
          description: Failed to process the application  
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  /v1/noc/_update:
    post:
      summary: Update existing application.
      description: Updates a given `application` with newer details.
      x-roles: 'BPA_ARCHITECT,CITIZEN,EMPLOYEE'
      tags:
        - Noc Apply
      responses:
        '202':
          description: Application updated successfully 
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/NocResponse'
        '400':
          description: Failed to update
          content:
            '*/*':
              schema:
                $ref: 'https://raw.githubusercontent.com/egovernments/egov-services/PT_APPLY_PAY/docs/common/contracts/v1-1-1.yml#/components/schemas/ErrorRes'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NocRequest'
        description: Request to update existing application details.
        required: true
  /v1/noc/_search:
    post:
      summary: Get the list of application by passing the diffrent search criteria.
      description: |
        Get the properties list based on the input parameters.
      tags:
        - Noc Apply
      operationId: searchUsingPOST
      parameters:
        - name: accountId
          in: query
          required: false
          style: pipeDelimited
          schema:
            type: array
            items:
              type: string
        - name: applicationNo
          in: query
          description: application numbers
          required: false
          style: form
          schema:
            type: string
        - name: ids
          in: query
          required: false
          style: pipeDelimited
          schema:
            type: array
            items:
              type: string
        - name: limit
          in: query
          required: false
          style: form
          schema:
            type: integer
            format: int32
        - name: mobileNumber
          in: query
          required: false
          style: form
          schema:
            type: string
        - name: nocNo
          in: query
          description: approval number
          required: false
          style: form
          schema:
            type: string
        - name: nocType
          in: query
          description: approval type
          required: false
          style: form
          schema:
            type: string
        - name: offset
          in: query
          description: offset
          required: false
          style: form
          schema:
            type: integer
            format: int32
        - name: ownerIds
          in: query
          description: Id credential for Owners
          required: false
          style: pipeDelimited
          schema:
            type: array
            items:
              type: string
        - name: source
          in: query
          description: 'Source mdms master data. Which captures the source of the service request(ex:- whatsapp, ivr, Swachhata etc)'
          required: false
          style: form
          schema:
            type: string
        - name: sourceRefId
          in: query
          description: 'Source reference Id'
          required: false
          style: form
          schema:
            type: string
        - name: status
          in: query
          description: current application status in the system records
          required: false
          style: pipeDelimited
          schema:
            type: array
            items:
              type: string
        - name: tenantId
          in: query
          description: "Unique id for a tenant."
          required: true
          style: form
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestInfoWrapper'
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/NocResponse'
        '201':
          description: Created
        '400':
          description: Invalid input    
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  
servers:
  - url: 'https://dev.digit.org'
components:
  schemas:
  
   Document:
      title: Document
      type: object
      properties:
        additionalDetails:
          type: object
          description: Json object to capture any extra information which is not accommodated by model
        documentType:
          type: string
          description: unique document type code, should be validated with document type master
        documentUid:
          maxLength: 64
          minLength: 0
          type: string
          description: The unique id(Pancard Number,Adhar etc.) of the given Document.
        fileStoreId:
          type: string
          description: File store reference key.
        id:
          maxLength: 64
          minLength: 0
          type: string
          description: system id of the Document.
      description: This object holds list of documents attached during the transaciton for a property 
   Noc:
      title: Noc
      type: object
      properties:
        accountId:
          maxLength: 64
          minLength: 1
          type: string
          description: Initiator User UUID
        additionalDetails:
          type: object
          description: The json to capturing the custom fields
        applicationNo:
          maxLength: 64
          minLength: 1
          type: string
          description: Generate formatted Unique Identifier of the Noc. Keep the format in mdms
          readOnly: true
        applicationStatus:
          maxLength: 64
          minLength: 1
          type: string
          description: Application status should get populate from wf engine
          readOnly: true
        applicationType:
          type: string
          description: noc application type.
          enum:
            - NEW
            - PROVISIONAL
            - RENEW
        auditDetails:
          $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/master/Common%20Services/common-contract.yaml#/components/schemas/AuditDetails'
        documents:
          type: array
          description: The documents attached by owner for exemption.
          items:
            $ref: '#/components/schemas/Document'
        id:
          maxLength: 64
          minLength: 1
          type: string
          description: Unique Identifier(UUID) of the bpa application for internal reference.
          readOnly: true
        landId:
          maxLength: 64
          minLength: 1
          type: string
          description: Unique Identifier(UUID) of the land for internal reference.
        nocNo:
          maxLength: 64
          minLength: 1
          type: string
          description: Generate Noc number based on wf status. When to generate Nocno will be depends on wf state so make it configurable at application level
          readOnly: true
        nocType:
          maxLength: 64
          minLength: 1
          type: string
          description: 'Mdms master data to configure types of noc(ex:fire noc, airport authority etc) '
        source:
          maxLength: 64
          minLength: 1
          type: string
          description: Who is creating the record in the system(ex:BPA,Property etc)
        sourceRefId:
          maxLength: 64
          minLength: 1
          type: string
          description: Unique Identifier of integrator(Source system) to link the noc application.
        status:
          type: string
          description: state of the record.
          enum:
            - ACTIVE
            - INACTIVE
        tenantId:
          maxLength: 256
          minLength: 2
          type: string
          description: Unique ULB identifier.
        workflow:
          $ref: '#/components/schemas/Workflow'
      description: NOC application object to capture the details of noc related information, landid and related documents.
   NocRequest:
      title: NocRequest
      type: object
      properties:
        Noc:
          $ref: '#/components/schemas/Noc'
        RequestInfo:
          $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/master/Common%20Services/common-contract.yaml#/components/schemas/RequestInfo'
      description: A object to bind the metadata contract and main application contract
   NocResponse:
      title: NocResponse
      type: object
      properties:
        Noc:
          type: array
          items:
            $ref: '#/components/schemas/Noc'
        ResponseInfo:
          $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/master/Common%20Services/common-contract.yaml#/components/schemas/ResponseInfo'
        count:
          type: integer
          format: int32
      description: Contains the ResponseMetadate and the main application contract
   RequestInfoWrapper:
      title: RequestInfoWrapper
      type: object
      properties:
        RequestInfo:
          $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/master/Common%20Services/common-contract.yaml#/components/schemas/RequestInfo'
   Workflow:
      title: Workflow
      type: object
      properties:
        action:
          maxLength: 64
          minLength: 1
          type: string
          description: Action on the application in certain
        assignes:
          type: array
          items:
            type: string
        comment:
          maxLength: 64
          minLength: 1
          type: string
          description: Comment by actor.
        documents:
          type: array
          description: Attach the workflow varification documents.
          items:
            $ref: '#/components/schemas/Document'
      description: BPA application object to capture the details of land, land owners, and address of the land.
