openapi: 3.0.1
info:
  title: eGov Fire NOC module.
  description: |
    APIs for Fire NOC module. This modules handles Below functionality.
      1. Apply Fire NOC.
      2. Search existing Fire NOC with different fiters.
      3. Update exiting Fire NOC.
  contact:
    name: eGovernments Foundation
    email: contacts@egovernments.org
  version: 1.0.0
servers:
- url: /firenoc-services
tags:
- name: Fire NOC
  description: APIs required for Fire NOC.
paths:
  /v1/_search:
    post:
      tags:
      - Fire NOC
      summary: Get the list of Fire NOC(s) defined in the system.
      description: 1. Search and get Fire NOC(s)  based on defined search criteria.
      parameters:
      - name: tenantId
        in: query
        description: Unique id for a tenant.
        required: true
        schema:
          type: string
          format: varchar
      - name: pageNumber
        in: query
        description: Page number
        schema:
          type: integer
          default: 1
      - name: status
        in: query
        description: Search based on status.
        allowEmptyValue: true
        schema:
          type: string
      - name: ids
        in: query
        description: unique identifier of Fire NOC
        style: form
        explode: false
        schema:
          maxItems: 50
          type: array
          items:
            type: string
      - name: applicationNumber
        in: query
        description: Unique application number for a Fire NOC application.
        schema:
          maxLength: 64
          minLength: 2
          type: string
      - name: fireNOCNumber
        in: query
        description: The unique  license number  for a Fire NOC.
        schema:
          maxLength: 64
          minLength: 2
          type: string
      - name: mobileNumber
        in: query
        description: The mobile number of a Fire NOC owner.
        schema:
          pattern: '[0-9]'
          type: string
      - name: fireNOCType
        in: query
        description: Fire NOC type.
        schema:
          type: string
      requestBody:
        description: Parameter to carry Request metadata in the request body
        content:
          '*/*':
            schema:
              $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/master/Common%20Services/common-contract.yaml#/components/schemas/RequestInfo'
        required: false
      responses:
        200:
          description: Fire NOC(s) Retrived Successfully
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/FireNOCResponse'
        400:
          description: Invalid input.
          content:
            '*/*':
              schema:
                $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/master/Common%20Services/common-contract.yaml#/components/schemas/ErrorRes'
      x-codegen-request-body-name: requestInfo
  /v1/_create:
    post:
      tags:
      - Fire NOC
      summary: Create new Fire NOC.
      description: |
        To create new Fire NOC in the system. API supports bulk creation with max limit as defined in the Fire NOC Request. Please note that either whole batch succeeds or fails, there's no partial batch success. To create one Fire NOC, please pass array with one Fire NOC object.


        Following Conditions are applied -
          1. Support Documents for a given Fire NOC will created. In case of not attaching the Mandatory Supported Documents creation of Fire NOC Fails.
          2. Noc Number will be autogenerated on final approval for new License.
          3. ApplicationNumber will be autogenerated for new Fire NOC
      requestBody:
        description: Details for the new Fire NOC(s) + RequestInfo meta data.
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/FireNOCRequest'
        required: true
      responses:
        201:
          description: ReponseInfo with Fire NOC(s) created successfully
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/FireNOCResponse'
        400:
          description: Fire NOC(s) creation failed
          content:
            '*/*':
              schema:
                $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/master/Common%20Services/common-contract.yaml#/components/schemas/ErrorRes'
      x-codegen-request-body-name: FireNOCRequest
  /v1/_update:
    post:
      tags:
      - Fire NOC
      summary: update existing Fire NOCs.
      description: |
        To update existing Fire NOC in the system. API supports bulk updation with max limit as defined in the Fire NOC Request. Please note that either whole batch succeeds or fails, there's no partial batch success. To update one Fire NOC, please pass array with one Fire NOC object.

        Following Conditions are applied -
          1. Before payment Employee or Citizen can update any details of Fire NOC
          2. After payment Citizen or Employee can't change any details of Fire NOC.
      requestBody:
        description: Details for the new Fire NOC(s) + RequestInfo meta data.
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/FireNOCRequest'
        required: true
      responses:
        201:
          description: ReponseInfo with Fire NOC(s) updated sudcessfully
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/FireNOCResponse'
        400:
          description: Fire NOC(s) updation failed
          content:
            '*/*':
              schema:
                $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/master/Common%20Services/common-contract.yaml#/components/schemas/ErrorRes'
      x-codegen-request-body-name: FireNOCRequest
components:
  schemas:
    Buildings:
      required:
      - name
      - tenantId
      - uoms
      - usageType
      type: object
      properties:
        id:
          maxLength: 64
          minLength: 2
          type: string
          description: Unique Identifier of the Fire NOC building details (UUID)
          readOnly: true
        tenantId:
          maxLength: 128
          minLength: 2
          type: string
          description: Unique Identifier of ULB
        name:
          type: string
          description: name of the building
        usageType:
          type: string
          description: building usage type
        uoms:
          type: array
          items:
            $ref: '#/components/schemas/BuildingUOM'
        applicationDocuments:
          type: array
          description: 1. List of all the required documents. 2. Application can be
            submitted without required document 3. Once all the document submitted
            then only application submition process will be completed. 4. Mandatry
            application documents for a fireNOC type and fireNOC subtype are defined
            under ApplicationDocument master which is defined under MDMS.
          items:
            $ref: '#/components/schemas/Document'
      description: It will contains building details
    PropertyDetails:
      type: object
      properties:
        id:
          maxLength: 64
          minLength: 2
          type: string
          description: Unique Identifier of the property details (UUID)
          readOnly: true
        propertyId:
          type: string
        address:
          $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/master/Common%20Services/common-contract.yaml#/components/schemas/Address'
      description: It will have fire noc related entities
    OwnerInfo:
      allOf:
      - $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/master/Common%20Services/common-contract.yaml#/components/schemas/User'
      - type: object
        properties:
          isPrimaryOwner:
            type: boolean
            description: The owner is primary or not
          ownerShipPercentage:
            type: number
            description: Ownership percentage.
            format: double
          ownerType:
            maxLength: 256
            minLength: 4
            type: string
            description: Type of owner, based on this option Exemptions will be applied.
              This is master data defined in mdms.
          relationship:
            type: string
            description: Relationship with owner.
            enum:
            - FATHER
            - HUSBAND
          documents:
            type: object
            description: Document of the owner.
    Document:
      required:
      - documentType
      - fileStoreId
      - tenantId
      type: object
      properties:
        tenantId:
          maxLength: 128
          minLength: 2
          type: string
          description: Unique Identifier of ULB
        documentType:
          maxLength: 64
          minLength: 2
          type: string
          description: 1.Unique document type code from common master. 2. This is
            defined under mdms common master. 3. Object defination is defined under
            'https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-1-1.yml#/definitions/DocumentType'
        fileStoreId:
          maxLength: 64
          minLength: 2
          type: string
          description: Unique file store id of uploaded document.
        documentUid:
          maxLength: 64
          minLength: 2
          type: string
          description: document number(eg.Pan number, aadhar number).
        auditDetails:
          $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/master/Common%20Services/common-contract.yaml#/components/schemas/AuditDetails'
      description: A Object holds the basic data for a Fire NOC
    FireNOC:
      required:
      - dateOfApplied
      - fireNOCDetails
      - tenantId
      type: object
      properties:
        id:
          maxLength: 64
          minLength: 2
          type: string
          description: Unique Identifier of the Fire NOC (UUID)
          readOnly: true
        tenantId:
          maxLength: 128
          minLength: 2
          type: string
          description: Unique Identifier of ULB
        fireNOCNumber:
          maxLength: 64
          minLength: 2
          type: string
          description: Unique Fire NOC Number of the Fire NOC. This is  unique in
            system for a tenant. This is mandatory but always be generated on the
            final approval.
          readOnly: true
        provisionFireNOCNumber:
          maxLength: 64
          minLength: 2
          type: string
          description: Unique Fire NOC Number of the Provision Fire NOC number that
            will be used for linking provision fire NOC number with new fire NOC number.
            This is  unique in system for a tenant. This is mandatory but always be
            generated on the final approval.
        oldFireNOCNumber:
          maxLength: 64
          minLength: 2
          type: string
          description: Unique Old License Number of the Fire NOC. This is  unique
            in system for a tenant. This is mandatory  for legacy license(DataEntry).
        dateOfApplied:
          type: integer
          description: Applied Date of the fire NOC as epoch
          format: int64
        fireNOCDetails:
          $ref: '#/components/schemas/FireNOCDetails'
        auditDetails:
          $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/master/Common%20Services/common-contract.yaml#/components/schemas/AuditDetails'
      description: A Object holds the basic data for a Fire NOC
    FireNOCDetails:
      required:
      - action
      - applicantDetails
      - channel
      - financialYear
      - fireNOCType
      - firestationId
      - propertyDetails
      type: object
      properties:
        id:
          maxLength: 64
          minLength: 2
          type: string
          description: Unique Identifier of the Fire FireNOC Details (UUID)
          readOnly: true
        applicationNumber:
          maxLength: 64
          minLength: 2
          type: string
          description: Unique Application FireNOC Number of the Fire FireNOC. This
            is  unique in system for a tenant. This is mandatory but always be generated
            on the final approval.
          readOnly: true
        fireNOCType:
          type: string
          description: type of fire NOC from mdms
        firestationId:
          type: string
          description: Fire station id where we are applying fire fireNOC.
        applicationDate:
          type: integer
          description: date on which applicaiton has been generated for new Fire NOC.
          format: int64
          readOnly: true
        financialYear:
          maxLength: 64
          minLength: 2
          type: string
          description: Fire NOC applicable for financial year.
        issuedDate:
          type: integer
          description: 1. License issued Date of the Fire NOC as epoch. 2. Application
            approval date.
          format: int64
          readOnly: true
        validFrom:
          type: integer
          description: Date from when Fire NOC is valid as epoch
          format: int64
        validTo:
          type: integer
          description: Expiry Date of the Fire NOC as epoch
          format: int64
        action:
          type: string
          description: 1. Perform action to change the state of the Fire NOC. 2. INITIATE,
            if application is getting submitted without required document. 3. APPLY,
            if application is getting submitted with application documents, in that
            case api will validate all the required application document. 4. APPROVE
            action is only applicable for specific role, that role has to be configurable
            at service level. Employee can approve a application only if application
            is in APPLIED state and Fire NOC fees is paid.
          enum:
          - INITIATE
          - APPLY
          - APPROVE
          - REJECT
          - CANCEL
        channel:
          maxLength: 64
          minLength: 2
          type: string
          description: License can be created from different channels
          enum:
          - COUNTER
          - CITIZEN
          - DATAENTRY
        noOfBuildings:
          type: string
          description: it might be single or multiple
        buildings:
          type: array
          items:
            $ref: '#/components/schemas/Buildings'
        propertyDetails:
          $ref: '#/components/schemas/PropertyDetails'
        applicantDetails:
          type: object
          properties:
            ownerShipType:
              type: string
              description: type pf the owner ship
            owners:
              type: array
              description: Fire NOC owners, these will be citizen users in system.
              items:
                $ref: '#/components/schemas/OwnerInfo'
            additionalDetail:
              type: object
              properties: {}
              description: Json object to store additional details about license,
                this will be used when ownership is intitution or others
          description: This will have details about applicant details
        additionalDetail:
          type: object
          properties: {}
          description: Json object to store additional details about license
        auditDetails:
          $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/master/Common%20Services/common-contract.yaml#/components/schemas/AuditDetails'
      description: A Object holds the basic data for a Fire NOC
    FireNOCRequest:
      required:
      - FireNOCs
      - RequestInfo
      type: object
      properties:
        RequestInfo:
          $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/master/Common%20Services/common-contract.yaml#/components/schemas/RequestInfo'
        FireNOCs:
          type: array
          description: Used for search result and create only
          items:
            $ref: '#/components/schemas/FireNOC'
      description: Contract class to receive request. Array of Noc items are used
    FireNOCResponse:
      type: object
      properties:
        ResponseInfo:
          $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/master/Common%20Services/common-contract.yaml#/components/schemas/ResponseInfo'
        FireNOCs:
          type: array
          description: Used for search result and create only
          items:
            $ref: '#/components/schemas/FireNOC'
      description: Contract class to send response. Array of Fire NOC items are used
        in case of search results or response for create, whereas single Fire NOC
        item is used for update
    BuildingUOM:
      type: object
      properties:
        code:
          type: string
          description: Code of the unit code
        value:
          type: string
          description: Value entered for the uom
        isActiveUom:
          type: boolean
          description: Active uom for current usage type
        active:
          type: boolean
      description: This master will have list of UOM's
    Boundary:
      required:
      - code
      - name
      type: object
      properties:
        code:
          type: string
          description: code of the boundary.
        name:
          type: string
          description: name of the boundary.
        label:
          type: string
          description: localized label for the boundry.
        latitude:
          type: string
          description: latitude of the boundary.
        longitude:
          type: string
          description: longitude of the boundary.
        children:
          type: array
          items:
            $ref: '#/components/schemas/Boundary'
        materializedPath:
          type: string
          description: materialized path of the boundary - this would be of the format
            tenantid.[code] from parentt till teh current boundary
          readOnly: true
  parameters:
    pageSize:
      name: pageSize
      in: query
      description: Number of records returned.
      schema:
        multipleOf: 10.0
        maximum: 100
        exclusiveMaximum: false
        minimum: 0
        exclusiveMinimum: true
        type: integer
        default: 20
    pageNumber:
      name: pageNumber
      in: query
      description: Page number
      schema:
        type: integer
        default: 1
    sortProperty:
      name: sort
      in: query
      description: Fire NOC results will be sorted by fireNOCNumber ascending by default
        if this parameter is not provided.
      style: pipeDelimited
      schema:
        maxItems: 3
        minItems: 1
        uniqueItems: true
        type: array
        items:
          pattern: '[-+](fireNOCNumber|fireNOCType|ownerName)'
          type: string
        default: '["+fireNOCNumber"]'
x-api-id: org.egov.firenoc.services
x-common-path: https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-1-1.yml
