openapi: 3.0.1
info:
  title: Campaign Manager
  description: BFF service APIs - to Bulk create, search and fetch all data in a registry.
  contact:
    name: eGov
    email: info@egovernments.org
  version: 1.0.0
servers:
- url: /campaign-manager/v1
paths:
  /campaign-manager/data/v1/_create:
    post:
      tags:
      - Bulk Data Creation
      summary: "This API endpoint used to do a bulk upload of data based on type"
      description: "This API endpoint used to do a bulk upload of data based on type"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                RequestInfo:
                  $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/master/Common%20Services/common-contract.yaml#/components/schemas/RequestInfo'
                ResourceDetails:
                  $ref: '#/components/schemas/ResourceDetails'
      responses:
        200:
          description: Successful Response.
          content:
            '*/*':
              schema:
                type: object
                properties:
                  ResponseInfo:
                    $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/master/Common%20Services/common-contract.yaml#/components/schemas/ResponseInfo'
                  ResponseDetails:
                    $ref: '#/components/schemas/CreateResponseDetails'
        400:
          description: Invalid input.
          content:
            '*/*':
              schema:
                $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/master/Common%20Services/common-contract.yaml#/components/schemas/ErrorRes'
  /campaign-manager/data/v1/_search:
    post:
      tags:
      - Bulk Data Creation
      summary: "This API endpoint searches for API resources"
      description: "This API endpoint searches for API resources"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                RequestInfo:
                  $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/master/Common%20Services/common-contract.yaml#/components/schemas/RequestInfo'
                SearchCriteria:
                  $ref: '#/components/schemas/SearchCriteria'
      responses:
        200:
          description: Successful Response.
          content:
            '*/*':
              schema:
                type: object
                properties:
                  ResponseInfo:
                    $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/master/Common%20Services/common-contract.yaml#/components/schemas/ResponseInfo'
                  ResponseDetails:
                    $ref: '#/components/schemas/SearchResponse'
        400:
          description: Invalid input.
          content:
            '*/*':
              schema:
                $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/master/Common%20Services/common-contract.yaml#/components/schemas/ErrorRes'
  /campaign-manager/data/v1/_generate:
    post:
      tags:
      - Bulk Data retrieval
      summary: "This API endpoint updates the API resources table"
      description: "This API endpoint updates the API resources table"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                RequestInfo:
                  $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/master/Common%20Services/common-contract.yaml#/components/schemas/RequestInfo'
      parameters:
      - name: tenantId
        in: query
        description: unique id for a tenant.
        required: true
        schema:
          maxLength: 256
          type: string
          format: varchar
      - name: type
        in: query
        description: type of the resource
        required: true
        schema:
          maxLength: 256
          type: string
          format: varchar
      - name: forceUpdate
        in: query
        description: "ForceUpdate parameter"
        required: false
        schema:
          type: boolean
      responses:
        200:
          description: Successful Response.
          content:
            '*/*':
              schema:
                type: object
                properties:
                  ResponseInfo:
                    $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/master/Common%20Services/common-contract.yaml#/components/schemas/ResponseInfo'
                  GeneratedResource:
                    $ref: '#/components/schemas/GeneratedResource'
        400:
          description: Invalid input.
          content:
            '*/*':
              schema:
                $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/master/Common%20Services/common-contract.yaml#/components/schemas/ErrorRes'
  /campaign-manager/data/v1/_download:
    post:
      tags:
      - Bulk Data retrieval
      summary: "This API endpoint updates the API resources table"
      description: "This API endpoint updates the API resources table"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                RequestInfo:
                  $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/master/Common%20Services/common-contract.yaml#/components/schemas/RequestInfo'
      parameters:
      - name: tenantId
        in: query
        description: unique id for a tenant.
        required: true
        schema:
          maxLength: 256
          type: string
          format: varchar
      - name: type
        in: query
        description: type of the resource
        required: true
        schema:
          maxLength: 256
          type: string
          format: varchar
      - name: id
        in: query
        description: unique id of the generated request
        required: false
        schema:
          maxLength: 256
          type: string
          format: varchar
      responses:
        200:
          description: Successful Response.
          content:
            '*/*':
              schema:
                type: object
                properties:
                  ResponseInfo:
                    $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/master/Common%20Services/common-contract.yaml#/components/schemas/ResponseInfo'
                  GeneratedResource:
                    $ref: '#/components/schemas/GeneratedResource'
        400:
          description: Invalid input.
          content:
            '*/*':
              schema:
                $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/master/Common%20Services/common-contract.yaml#/components/schemas/ErrorRes'
  /campaign-manager/process/v1/create-campaign:
    post:
      tags:
      - Process Campaign
      summary: "This API endpoint used to do a bulk upload of data based on type"
      description: "This API endpoint used to do a bulk upload of data based on type"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                RequestInfo:
                  $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/master/Common%20Services/common-contract.yaml#/components/schemas/RequestInfo'
                ResourceDetails:
                  $ref: '#/components/schemas/CampaignResourceDetails'
      responses:
        200:
          description: Successful Response.
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/BulkResourceCreateResponse'
        400:
          description: Invalid input.
          content:
            '*/*':
              schema:
                $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/master/Common%20Services/common-contract.yaml#/components/schemas/ErrorRes'
  /campaign-manager/process/v1/search-campaign:
    post:
      tags:
      - Process Campaign
      summary: "This API endpoint searches for API resources"
      description: "This API endpoint searches for API resources"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/SearchRequest"   
      responses:
        200:
          description: Successful Response.
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/BulkResourceCreateResponse'
        400:
          description: Invalid input.
          content:
            '*/*':
              schema:
                $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/master/Common%20Services/common-contract.yaml#/components/schemas/ErrorRes'
components:
  schemas:
    ResourceDetails:
      type: object
      properties:
        id:
          type: "string"
          format: uuid
          description: System generated unique identifier for the entry
          readOnly: true
        type:
          type: "string"
          example: "facility|user|boundary"
        tenantId:
          type: "string"
        fileStoreId:
          type: "string"
          format: uuid
          description: input file
        action:
          type: "string"
          enum: 
            - "create"
            - "validate"
    CampaignResourceDetails:
      type: object
      properties:
        hierarchyType:
          type: "string"
        tenantId:
          type: "string"
        campaignName:
          type: "string"
        action:
          type: "string"
          example: "draft||create"
        startDate:
          type: number
          format: timestamp
          example: 1665497225000
          description: Timestamp of the start date in milliseconds
        endDate: 
          type: number
          format: timestamp
          example: 1665497225000
          description: Timestamp of the start date in milliseconds
        resources:
          type: "array"
          items:
            type: "object"
            properties:
              filestoreId:
                type: "string"
                example: "cf3bd20c-5ac3-4af1-a303-55445049b289"
              type:
                type: "string"
                example: "user"
              filename:
                type: "string"
                example: "user.xlsx"
        projectType:
          type: "string"
        deliveryRules:
          type: "array"
          items:
            type: "object"
            properties:
              startDate:
                type: number
                format: timestamp
                example: 1665497225000
                description: Timestamp of the start date in milliseconds
              endDate: 
                type: number
                format: timestamp
                example: 1665497225000
                description: Timestamp of the start date in milliseconds
              cycleNumber:
                type: "number"
              deliveryNumber:
                type: "number"
              products:
                type: "array"
                items:
                  type: "string"
              conditions:
                type: "array"
                items:
                  type: "object"
                  properties:
                    attribute:
                      type: "string"
                    operator:
                      type: "string"
                    value:
                      type: "number" 
        additionalDetails:
          type: "object"
    BulkResourceCreateResponse:
      type: object
      properties:
        ResponseInfo:
          $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/master/Common%20Services/common-contract.yaml#/components/schemas/ResponseInfo'
        ResponseDetails:
          $ref: '#/components/schemas/CreateResponseDetails'
    CreateResponseDetails:
      type: "object"
      properties:
        id:
          type: "string"
          example: "cf3bd20c-5ac3-4af1-a303-55445049b289"
        tenantId:
          type: "string"
        status:
          type: "string"
          example: "data-accepted"
        processReferenceNumber:
          type: "string"
          example: "PRO-001-001-001"
        fileStoreId:
          type: "string"
          example: "a47e3f92-5c05-4abf-bf4e-17d2d4a35a72"
        type:
          type: "string"
          example: "facility"

    SearchCriteria:
      type: "object"
      properties:
        id:
          type: "array"
          items:
            type: "string"
        tenantId:
          type: "string"
        processReferenceNumber:
          type: "string"
        type:
          type: "string"
    SearchResponse:
      type: "array"
      items:
        type: "object"
        properties:
          status:
            type: "string"
            example: "data-accepted"
          id:
            type: "string"
            example: "cf3bd20c-5ac3-4af1-a303-55445049b289"
          tenantId:
            type: "string"
          processReferenceNumber:
            type: "string"
            example: "PRO-001-001-001"
          fileStoreId:
            type: "string"
            example: "a47e3f92-5c05-4abf-bf4e-17d2d4a35a72"
            format: uuid
            description: input file
          processedFileStoreId:
            type: "string"
            example: "a47e3f92-5c05-4abf-bf4e-17d2d4a35a72"
            format: uuid
            description: processed file with updated status
          type:
            type: "string"
            example: "facility"
          additionalDetails:
            type: "object"
            example: {}
          auditDetails:
            type: "object"
            properties:
              createdBy:
                type: "string"
                example: "a1b2c3d4-e5f6-g7h8-i9j0-k1l2m3n4o5p6"
              lastModifiedBy:
                type: "string"
                example: "a1b2c3d4-e5f6-g7h8-i9j0-k1l2m3n4o5p6"
              createdTime:
                type: "string"
                example: "1644426612"
              lastModifiedTime:
                type: "string"
                example: "1644426612"
    GeneratedResource:
      type: "object"
      properties:
        id:
          type: "string"
          example: "c0ab3641-97bb-4601-9a8a-60bb9db59708"
        tenantId:
          type: "string"
          example: "pg.citya"
        fileStoreid:
          type: "string"
          example: "c0ab3641-97bb-4601-9a8a-60bb9db59708"
        type:
          type: "string"
          example: "facility"
        status:
          type: "string"
          example: "completed"
        count:
          type: "number"
          example: 100
        additionalDetails:
          type: "object"
          example : {}
        auditDetails:
          type: "object"
          properties:
            createdBy:
              type: "string"
              example: "a1b2c3d4-e5f6-g7h8-i9j0-k1l2m3n4o5p6"
            lastModifiedBy:
              type: "string"
              example: "a1b2c3d4-e5f6-g7h8-i9j0-k1l2m3n4o5p6"
            createdTime:
              type: "string"
              example: "1644426612"
            lastModifiedTime:
              type: "string"
              example: "1644426612"
    Campaign:
      type: object
      properties:
        id:
          type: "string"
          format: uuid
          description: System generated unique identifier for the entry
          readOnly: true
        campaignNo:
          type: "string"
          example: CAM/2022-23/001
          description: System generated id with custom formatting
          readOnly: true
        referenceId:
          type: "string"
          format: uuid
          description: microplan id or bulk campaign process id
        hierarchyType:
          type: "string"
          example: admin
        tenantId:
          type: "string"
          example: mz
        campaignName:
          type: "string"
          example: bednet campaign
        boundaryCode:
          type: "string"
          example: "mz" 
          description: "root boundary code"
        startDate:
          type: number
          format: timestamp
          example: 1665497225000
          description: Timestamp of the start date in milliseconds
        endDate: 
          type: number
          format: timestamp
          example: 1665497225000
          description: Timestamp of the start date in milliseconds
        projectType:
          type: "string"
        CampaignDetails:
          $ref: '#/components/schemas/CampaignDetails'
        deliveryRules:
          type: "array"
          items:
            type: "object"
            properties:
              startDate:
                type: number
                format: timestamp
                example: 1665497225000
                description: Timestamp of the start date in milliseconds
              endDate:
                type: number
                format: timestamp
                example: 1665497225000
                description: Timestamp of the start date in milliseconds              
              cycle:
                type: "string"
        additionalDetails:
          type: "object"
    CampaignDetails:
      type: "array"
      items:
        type: "object"
        properties:
          id:
            type: "string"
            format: uuid
            description: System generated unique identifier for the entry
            readOnly: true
          boundaryCode:
            type: "string"
            example: "nampula"
          boundaryType:
            type: "string"
            example: "country|province"
          startDate:
            type: number
            format: timestamp
            example: 1665497225000
            description: Timestamp of the start date in milliseconds
          endDate:
            type: number
            format: timestamp
            example: 1665497225000
            description: Timestamp of the start date in milliseconds
          targets:
            type: "array"
            items:
              type: "object"
              properties:
                total:
                  type: "number"
                  example: 1000
                target:
                  type: "number"
                  example: 800
                type:
                  type: "string"
                  example: "household|individual"
          parentBoundaryCode:
            type: "string"
            example: "mz"
          projectId:
             type: "string"
          resources:
            type: "array"
            items:
              type: "object"
              properties:
                id:
                  type: "string"
                  format: uuid
                  description: System generated unique identifier for the entry
                  readOnly: true
                resourceIds:
                  type: "array"
                  items:
                    type: "string"
                    format: uuid
                    description: unique id of the relationship entity
                count:
                  type: "number"
                active:
                  type: "boolean"
                type:
                  type: "string"
                  example: "staff|resource|facility"
