swagger: '2.0'
info:
  version: 1.1.2
  title: Facility Registry
  description: >
    This module facilitates maintenance of a Facility registry.
  contact:
    name: Digit
    email: info@egovernments.org
schemes:
  - https
x-common-path: >-
  https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml
paths:
  /facility/v1/_create:
    post:
      summary: >-
        Create/Add a new facility
      description: >-
        Create a new facility
      parameters:
        - name: Facility
          in: body
          description: Capture details of Facility.
          required: true
          schema:
              $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/master/Domain%20Services/Health/common/health-services-models-1.0.20.yaml#/components/schemas/FacilityRequest'
      tags:
        - Facility
      responses:
        '202':
          description: Facility request has been accepted.
          schema:
            $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/master/Domain%20Services/Health/common/health-services-models-1.0.20.yaml#/components/schemas/FacilityResponse'
        '400':
          description: Invalid Input body.
          schema:
            $ref: >-
              https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-1-1.yml#/definitions/ErrorRes
  /facility/v1/bulk/_create:
    post:
      summary: >-
        Create/Add new facilities in bulk
      description: >-
        Create a new facilities in bulk
      parameters:
        - name: Facility
          in: body
          description: Capture details of Facility.
          required: true
          schema:
            $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/master/Domain%20Services/Health/common/health-services-models-1.0.20.yaml#/components/schemas/FacilityBulkRequest'
      tags:
        - Facility
      responses:
        '202':
          description: Facility request has been accepted.
          schema:
            $ref: '#/definitions/BulkAcceptedResponse'
        '400':
          description: Invalid Input body.
          schema:
            $ref: >-
              https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-1-1.yml#/definitions/ErrorRes
  /facility/v1/_update:
    post:
      summary: >-
        Update the details of a existing facility
      description: >-
        Update the details of a existing facility
      parameters:
        - name: Facility
          in: body
          description: Details for existing facility.
          required: true
          schema:
            $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/master/Domain%20Services/Health/common/health-services-models-1.0.20.yaml#/components/schemas/FacilityRequest'
      tags:
        - Facility
      responses:
        '202':
          description: Facility request accepted.
          schema:
            $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/master/Domain%20Services/Health/common/health-services-models-1.0.20.yaml#/components/schemas/FacilityResponse'
        '400':
          description: Invalid Input body.
          schema:
            $ref: >-
              https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-1-1.yml#/definitions/ErrorRes
  /facility/v1/bulk/_update:
    post:
      summary: >-
        Update the details of  existing facilities in bulk
      description: >-
        Update the details of a existing facilities in bulk
      parameters:
        - name: Facility
          in: body
          description: Details for existing facility.
          required: true
          schema:
            $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/master/Domain%20Services/Health/common/health-services-models-1.0.20.yaml#/components/schemas/FacilityBulkRequest'
      tags:
        - Facility
      responses:
        '202':
          description: Facility request accepted.
          schema:
            $ref: '#/definitions/BulkAcceptedResponse'
        '400':
          description: Invalid Input body.
          schema:
            $ref: >-
              https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-1-1.yml#/definitions/ErrorRes
  /facility/v1/_delete:
    post:
      summary: >-
        Soft delete details of an existing facility
      description: >-
        Soft delete details of an existing facility
      parameters:
        - name: Facility
          in: body
          description: Details for existing facility.
          required: true
          schema:
            $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/master/Domain%20Services/Health/common/health-services-models-1.0.20.yaml#/components/schemas/FacilityRequest'
      tags:
        - Facility
      responses:
        '202':
          description: Facility request accepted.
          schema:
            $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/master/Domain%20Services/Health/common/health-services-models-1.0.20.yaml#/components/schemas/FacilityResponse'
        '400':
          description: Invalid Input body.
          schema:
            $ref: >-
              https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-1-1.yml#/definitions/ErrorRes
  /facility/v1/bulk/_delete:
    post:
      summary: >-
        Soft delete details of existing facilities in bulk
      description: >-
        Soft delete details of an existing facilities in bulk
      parameters:
        - name: Facility
          in: body
          description: Details for existing facility.
          required: true
          schema:
            $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/master/Domain%20Services/Health/common/health-services-models-1.0.20.yaml#/components/schemas/FacilityBulkRequest'
      tags:
        - Facility
      responses:
        '202':
          description: Facility request accepted.
          schema:
            $ref: '#/definitions/BulkAcceptedResponse'
        '400':
          description: Invalid Input body.
          schema:
            $ref: >-
              https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-1-1.yml#/definitions/ErrorRes
  /facility/v1/_search:
    post:
      summary: >-
        Search existing facility
      description: >-
        Search existing facility
      parameters:
        - name: Facility
          in: body
          description: Details for existing facility.
          required: true
          schema:
            $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/master/Domain%20Services/Health/common/health-services-models-1.0.20.yaml#/components/schemas/FacilitySearchRequest'
        - $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/master/Domain%20Services/Health/common/health-services-models-1.0.20.yaml#/components/schemas/UrlParams/properties/limit'
        - $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/master/Domain%20Services/Health/common/health-services-models-1.0.20.yaml#/components/schemas/UrlParams/properties/offset'
        - $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/master/Domain%20Services/Health/common/health-services-models-1.0.20.yaml#/components/schemas/UrlParams/properties/tenantId'
        - $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/master/Domain%20Services/Health/common/health-services-models-1.0.20.yaml#/components/schemas/UrlParams/properties/lastChangedSince'
        - $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/master/Domain%20Services/Health/common/health-services-models-1.0.20.yaml#/components/schemas/UrlParams/properties/includeDeleted'
      tags:
        - Facility
      responses:
        '200':
          description: Facilities.
          schema:
            $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/master/Domain%20Services/Health/common/health-services-models-1.0.20.yaml#/components/schemas/FacilityBulkResponse'
        '400':
          description: Invalid Input body.
          schema:
            $ref: >-
              https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-1-1.yml#/definitions/ErrorRes

parameters:
  #TODO is tenantId required as a query param if it can be determine from requestInfo->userInfo
  echoResource:
    name: echoResource
    in: query
    type: boolean
    required: false
    default: true
    description: Client can specify if the resource in request body needs to be sent back in the response. This is being used to limit amount of data that needs to flow back from the server to the client in low bandwidth scenarios. Server will always send the server generated id for validated requests.

  serverHandlesErrors:
    name: serverHandlesErrors
    in: query
    type: boolean
    required: false
    default: false
    description: Client can specify that it is incapable of handling any errors with the requests and server should route these for manual intervention if required.



definitions:
  id:
    $ref: 'https://raw.githubusercontent.com/digit-egov/health-api-specs/main/contracts/common.yaml#/definitions/id'
  idForSearch:
    $ref: 'https://raw.githubusercontent.com/digit-egov/health-api-specs/main/contracts/common.yaml#/definitions/idForSearch'
  boundaryCode:
    $ref: 'https://raw.githubusercontent.com/digit-egov/health-api-specs/main/contracts/common.yaml#/definitions/boundaryCode'
  tenantId:
    $ref: 'https://raw.githubusercontent.com/digit-egov/health-api-specs/main/contracts/common.yaml#/definitions/tenantId'
  eventTimestamp:
    $ref: 'https://raw.githubusercontent.com/digit-egov/health-api-specs/main/contracts/common.yaml#/definitions/eventTimestamp'
  isDeleted:
    $ref: 'https://raw.githubusercontent.com/digit-egov/health-api-specs/main/contracts/common.yaml#/definitions/isDeleted'
  rowVersion:
    $ref: 'https://raw.githubusercontent.com/digit-egov/health-api-specs/main/contracts/common.yaml#/definitions/rowVersion'
  apiOperation:
    $ref: 'https://raw.githubusercontent.com/digit-egov/health-api-specs/main/contracts/common.yaml#/definitions/apiOperation'
  additionalFields:
    $ref: 'https://raw.githubusercontent.com/digit-egov/health-api-specs/main/contracts/common.yaml#/definitions/additionalFields'
  Address:
    $ref: 'https://raw.githubusercontent.com/digit-egov/health-api-specs/main/contracts/common.yaml#/definitions/Address'

  BoundaryRequest:
    type: object
    properties:
      requestInfo:
        $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/master/Domain%20Services/Health/common/health-services-models-1.0.20.yaml#/components/schemas/RequestInfo'
      boundary:
        type: array
        items:
          $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/master/Domain%20Services/Health/common/health-services-models-1.0.20.yaml#/components/schemas/Boundary'
    required:
      - requestInfo
      - boundary

  BoundaryResponse:
    type: object
    properties:
      responseInfo:
        $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/master/Domain%20Services/Health/common/health-services-models-1.0.20.yaml#/components/schemas/ResponseInfo'
      boundary:
        type: array
        items:
          $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/master/Domain%20Services/Health/common/health-services-models-1.0.20.yaml#/components/schemas/Boundary'

  BoundarySearchCriteria:
    type: object
    properties:
      codes:
        type: array
        items:
          type: string
        minItems: 1
      tenantId:
        type: string
      offset:
        type: integer
      limit:
        type: integer

  BulkAcceptedResponse:
    type: object
    properties:
      ResponseInfo:
        $ref: >-
          https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-1-1.yml#/definitions/ResponseInfo
    required:
      - ResponseInfo