swagger: '2.0'
info:
  version: 1.1.5
  title: Individual Registry
  description: >
    This module facilitates maintenance of an Individual registry.
  contact:
    name: Digit
    email: info@egovernments.org
schemes:
  - https
x-common-path: >-
  https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml
paths:
  /individual/v1/_create:
    post:
      summary: >-
        Create/Add a new Individual
      description: >-
        Create a new Individual
      parameters:
        - name: Individual
          in: body
          description: Capture details of Individual.
          required: true
          schema:
            $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/master/Domain%20Services/Health/common/health-services-models-1.0.20.yaml#/components/schemas/IndividualRequest'
        - $ref: '#/parameters/echoResource'
      tags:
        - Individual
      responses:
        '202':
          description: Accepted
          schema:
            $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/master/Domain%20Services/Health/common/health-services-models-1.0.20.yaml#/components/schemas/IndividualResponse'
        '400':
          description: Bad Request
          schema:
            $ref: >-
              https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-1-1.yml#/definitions/ErrorRes
        '500':
          description: Internal Server Error
          schema:
            $ref: >-
              https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-1-1.yml#/definitions/ErrorRes

  /individual/v1/bulk/_create:
    post:
      summary: >-
        Create/Add Individuals
      description: >-
        Create a new Individuals
      parameters:
        - name: Individual
          in: body
          description: Capture details of Individual.
          required: true
          schema:
            $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/master/Domain%20Services/Health/common/health-services-models-1.0.20.yaml#/components/schemas/IndividualBulkRequest'
        - $ref: '#/parameters/echoResource'
      tags:
        - Individual
      responses:
        '202':
          description: Accepted
          schema:
            $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/master/Domain%20Services/Health/common/health-services-models-1.0.20.yaml#/components/schemas/IndividualBulkResponse'
        '400':
          description: Bad Request
          schema:
            $ref: >-
              https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-1-1.yml#/definitions/ErrorRes
        '500':
          description: Internal Server Error
          schema:
            $ref: >-
              https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-1-1.yml#/definitions/ErrorRes

  /individual/v1/_update:
    post:
      summary: >-
        Update the details of a existing Individual
      description: >-
        Update the details of a existing Individual
      parameters:
        - name: Individual
          in: body
          description: Details for the Individual.
          required: true
          schema:
            $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/master/Domain%20Services/Health/common/health-services-models-1.0.20.yaml#/components/schemas/IndividualRequest'
        - $ref: '#/parameters/echoResource'
      tags:
        - Individual
      responses:
        '202':
          description: Accepted
          schema:
            $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/master/Domain%20Services/Health/common/health-services-models-1.0.20.yaml#/components/schemas/IndividualResponse'
        '400':
          description: Bad Request
          schema:
            $ref: >-
              https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-1-1.yml#/definitions/ErrorRes
        '500':
          description: Internal Server Error
          schema:
            $ref: >-
              https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-1-1.yml#/definitions/ErrorRes

  /individual/v1/bulk/_update:
    post:
      summary: >-
        Update the details of existing Individuals
      description: >-
        Update the details of existing Individuals
      parameters:
        - name: Individual
          in: body
          description: Details for the Individual.
          required: true
          schema:
            $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/master/Domain%20Services/Health/common/health-services-models-1.0.20.yaml#/components/schemas/IndividualBulkRequest'
        - $ref: '#/parameters/echoResource'
      tags:
        - Individual
      responses:
        '202':
          description: Accepted
          schema:
            $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/master/Domain%20Services/Health/common/health-services-models-1.0.20.yaml#/components/schemas/IndividualBulkResponse'
        '400':
          description: Bad Request
          schema:
            $ref: >-
              https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-1-1.yml#/definitions/ErrorRes
        '500':
          description: Internal Server Error
          schema:
            $ref: >-
              https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-1-1.yml#/definitions/ErrorRes

  /individual/v1/_delete:
    post:
      summary: >-
        Soft delete the details of a existing Individual and nested entities
      description: >-
        Soft delete the details of a existing Individual and nested entities
      parameters:
        - name: Individual
          in: body
          description: Details for the Individual.
          required: true
          schema:
            $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/master/Domain%20Services/Health/common/health-services-models-1.0.20.yaml#/components/schemas/IndividualRequest'
        - $ref: '#/parameters/echoResource'
      tags:
        - Individual
      responses:
        '202':
          description: Accepted
          schema:
            $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/master/Domain%20Services/Health/common/health-services-models-1.0.20.yaml#/components/schemas/IndividualResponse'
        '400':
          description: Bad Request
          schema:
            $ref: >-
              https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-1-1.yml#/definitions/ErrorRes
        '500':
          description: Internal Server Error
          schema:
            $ref: >-
              https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-1-1.yml#/definitions/ErrorRes

  /individual/v1/bulk/_delete:
    post:
      summary: >-
        Soft delete the details of a existing Individual and nested entities in bulk
      description: >-
        Soft delete the details of a existing Individual and nested entities in bulk
      parameters:
        - name: Individual
          in: body
          description: Details for the Individual.
          required: true
          schema:
            $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/master/Domain%20Services/Health/common/health-services-models-1.0.20.yaml#/components/schemas/IndividualBulkRequest'
        - $ref: '#/parameters/echoResource'
      tags:
        - Individual
      responses:
        '202':
          description: Accepted
          schema:
            $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/master/Domain%20Services/Health/common/health-services-models-1.0.20.yaml#/components/schemas/IndividualBulkResponse'
        '400':
          description: Bad Request
          schema:
            $ref: >-
              https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-1-1.yml#/definitions/ErrorRes
        '500':
          description: Internal Server Error
          schema:
            $ref: >-
              https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-1-1.yml#/definitions/ErrorRes

  /individual/v1/_search:
    post:
      summary: >-
        Search existing Individual
      description: >-
        Search existing Individual
      parameters:
        - name: Individual
          in: body
          description: Individual details.
          required: true
          schema:
            $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/master/Domain%20Services/Health/common/health-services-models-1.0.20.yaml#/components/schemas/IndividualSearchRequest'
        - $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/master/Domain%20Services/Health/common/health-services-models-1.0.20.yaml#/components/schemas/UrlParams/properties/limit'
        - $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/master/Domain%20Services/Health/common/health-services-models-1.0.20.yaml#/components/schemas/UrlParams/properties/offset'
        - $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/master/Domain%20Services/Health/common/health-services-models-1.0.20.yaml#/components/schemas/UrlParams/properties/tenantId'
        - $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/master/Domain%20Services/Health/common/health-services-models-1.0.20.yaml#/components/schemas/UrlParams/properties/lastChangedSince'
        - $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/master/Domain%20Services/Health/common/health-services-models-1.0.20.yaml#/components/schemas/UrlParams/properties/includeDeleted'
      tags:
        - Individual
      responses:
        '200':
          description: Ok
          schema:
            $ref: '#/definitions/IndividualBulkSearchResponse'
        '400':
          description: Bad Request
          schema:
            $ref: >-
              https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-1-1.yml#/definitions/ErrorRes
        '500':
          description: Internal Server Error
          schema:
            $ref: >-
              https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-1-1.yml#/definitions/ErrorRes

parameters:
  #TODO is tenantId required as a query param if it can be determine from requestInfo->userInfo


  echoResource:
    name: echoResource
    in: query
    type: boolean
    required: false
    default: true
    description: Client can specify if the resource in request body needs to be sent back in the response. This is being used to limit amount of data that needs to flow back from the server to the client in low bandwidth scenarios. Server will always send the server generated id for validated requests.

  serverHandlesErrors:
    name: serverHandlesErrors
    in: query
    type: boolean
    required: false
    default: false
    description: Client can specify that it is incapable of handling any errors with the requests and server should route these for manual intervention if required.



definitions:
  IndividualBulkSearchResponse:
    type: object
    properties:
      ResponseInfo:
        $ref: >-
          https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-1-1.yml#/definitions/ResponseInfo
      Individuals:
        type: array
        items:
          $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/master/Domain%20Services/Health/common/health-services-models-1.0.20.yaml#/components/schemas/Individual'
    required:
      - ResponseInfo