swagger: '2.0'
info:
  version: 1.0.2
  title: IRS Management System
  contact:
    name: egovernments foundation
    email: info@egovernments.org
schemes:
  - https
x-common-path: https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml
paths:
  /project/user-action/v1/_create:
    post:
      summary: Create User-Actions (ie. Closed Household) for the project in bulk
      description: Create User-Actions (ie. Closed Household) for the project in bulk
      parameters:
        - name: UserAction
          in: body
          description: Capture details of UserAction
          required: true
          schema:
            $ref: '#/definitions/UserActionBulkRequest'
      tags:
        - User Action
      responses:
        '202':
          description: Create User-Action (ie. Closed Household) request has been accepted for creation.
          schema:
            $ref: '#/definitions/BulkAcceptedResponse'
        '400':
          description: Invalid Input body.
          schema:
            $ref: https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-1-1.yml#/definitions/ErrorRes
  /project/user-action/v1/_update:
    post:
      summary: User-Action (ie. Closed Household) Request in bulk for a project
      description: User-Action (ie. Closed Household) Request in bulk for a project
      parameters:
        - name: UserAction
          in: body
          description: Capture details of Existing User-Actions (ie. Closed Household)
          required: true
          schema:
            $ref: '#/definitions/UserActionBulkRequest'
      tags:
        - User Action
      responses:
        '202':
          description: update User-Actions (ie. Closed Household) bulk request has been accepted for update.
          schema:
            $ref: '#/definitions/BulkAcceptedResponse'
        '400':
          description: Invalid Input body.
          schema:
            $ref: https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-1-1.yml#/definitions/ErrorRes
  /project/user-action/v1/_search:
    post:
      summary: Search User-Action (ie. Closed Household) for Project
      description: Search User-Action (ie. Closed Household) for Project
      parameters:
        - name: UserAction
          in: body
          description: User-Action (ie. Closed Household) Search.
          required: true
          schema:
            $ref: '#/definitions/UserActionSearchRequest'
        - $ref: '#/definitions/UrlParams/properties/limit'
        - $ref: '#/definitions/UrlParams/properties/offset'
        - $ref: '#/definitions/UrlParams/properties/tenantId'
        - $ref: '#/definitions/UrlParams/properties/lastChangedSince'
        - $ref: '#/definitions/UrlParams/properties/includeDeleted'
      tags:
        - User Action
      responses:
        '200':
          description: User-Actions (ie. Closed Household).
          schema:
            $ref: '#/definitions/UserActionBulkResponse'
        '400':
          description: Invalid Input body.
          schema:
            $ref: https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-1-1.yml#/definitions/ErrorRes

  /project/user-location/v1/_create:
    post:
      summary: Create User locations in bulk
      description: Create User locations in bulk
      parameters:
        - name: UserAction
          in: body
          description: Capture details of UserAction
          required: true
          schema:
            $ref: '#/definitions/UserActionBulkRequest'
      tags:
        - Location Capture
      responses:
        '202':
          description: Create Location Capture Task request has been accepted for creation.
          schema:
            $ref: '#/definitions/BulkAcceptedResponse'
        '400':
          description: Invalid Input body.
          schema:
            $ref: https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-1-1.yml#/definitions/ErrorRes
  /project/user-location/v1/_search:
    post:
      summary: Search Location Capture Task for Project
      description: Search Location Capture Task for Project
      parameters:
        - name: Task
          in: body
          description: Location Capture Task Search.
          required: true
          schema:
            $ref: '#/definitions/UserActionSearchRequest'
        - $ref: '#/definitions/UrlParams/properties/limit'
        - $ref: '#/definitions/UrlParams/properties/offset'
        - $ref: '#/definitions/UrlParams/properties/tenantId'
        - $ref: '#/definitions/UrlParams/properties/lastChangedSince'
        - $ref: '#/definitions/UrlParams/properties/includeDeleted'
      tags:
        - Location Capture
      responses:
        '200':
          description: UserActions.
          schema:
            $ref: '#/definitions/UserActionBulkResponse'
        '400':
          description: Invalid Input body.
          schema:
            $ref: https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-1-1.yml#/definitions/ErrorRes



parameters:
  echoResource:
    name: echoResource
    in: query
    type: boolean
    required: false
    default: true
    description: Client can specify if the resource in request body needs to be sent back in the response. This is being used to limit amount of data that needs to flow back from the server to the client in low bandwidth scenarios. Server will always send the server generated id for validated requests.
  serverHandlesErrors:
    name: serverHandlesErrors
    in: query
    type: boolean
    required: false
    default: false
    description: Client can specify that it is incapable of handling any errors with the requests and server should route these for manual intervention if required.
  includeEnded:
    name: includeEnded
    description: Used in project search API to specify if records past end date should be included in search results.
    in: query
    type: boolean
    default: false
    required: false
  includeAncestors:
    name: includeAncestors
    description: Used in project search API to specify if response should include project elements that are in the preceding hierarchy of matched projects.
    in: query
    type: boolean
    default: false
    required: false
  includeDescendants:
    name: includeDescendants
    description: Used in project search API to specify if response should include project elements that are in the following hierarchy of matched projects.
    in: query
    type: boolean
    default: false
    required: false
  createdFrom:
    name: createdFrom
    description: |
      Used in project search API to limit the search results to only those projects whose creation date is after the specified 'createdFrom' date.
    in: query
    required: false
    type: integer
    format: int64
  createdTo:
    name: createdTo
    description: |
      Used in project search API to limit the search results to only those projects whose creation date is before the specified 'createdTo' date.
    in: query
    required: false
    type: integer
    format: int64
definitions:
  BulkAcceptedResponse:
    type: object
    properties:
      ResponseInfo:
        $ref: https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-1-1.yml#/definitions/ResponseInfo
    required:
      - ResponseInfo
  Address:
    $ref: 'https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-1-1.yml#/definitions/Address'
  AuditDetails:
    $ref: 'https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-1-1.yml#/definitions/AuditDetails'
  RequestInfo:
    $ref: 'https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-1-1.yml#/definitions/RequestInfo'
  ResponseInfo:
    $ref: 'https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-1-1.yml#/definitions/ResponseInfo'
  Field:
    type: "object"
    required:
      - "key"
      - "value"
    properties:
      key:
        type: "string"
        example: "height"
        minLength: 2
        maxLength: 64
      value:
        type: "string"
        example: 180
        minLength: 2
        maxLength: 10000
  AdditionalFields:
    type: "object"
    properties:
      schema:
        type: "string"
        example: "HOUSEHOLD"
        minLength: 2
        maxLength: 64
      version:
        type: "integer"
        example: 2
        minimum: 1
      fields:
        type: "array"
        items:
          type: "object"
          $ref: '#/definitions/Field'
  EgovModel:
    type: object
    properties:
      id:
        type: string
        description: Unique identifier for the model
      tenantId:
        type: string
        description: Tenant ID for the model
      status:
        type: string
        description: Status of the model
      source:
        type: string
        description: Source of the model
      rowVersion:
        type: integer
        description: Version of the model
      applicationId:
        type: string
        description: Application ID of the model
      hasErrors:
        type: boolean
        description: Indicates if there are errors in the model
      additionalFields:
        $ref: '#/definitions/AdditionalFields'
      auditDetails:
        $ref: '#/definitions/AuditDetails'
    required:
      - tenantId
  EgovOfflineModel:
    allOf:
      - $ref: '#/definitions/EgovModel'
      - type: object
        properties:
          clientReferenceId:
            type: string
            description: Client reference ID for the model
          clientAuditDetails:
            $ref: '#/definitions/AuditDetails'
  EgovSearchModel:
    type: "object"
    properties:
      id:
        type: "array"
        items:
          type: "string"
          description: "List of IDs for searching entities."
        description: "A list of IDs used in search operations."
  EgovOfflineSearchModel:
    type: "object"
    allOf:
      - $ref: '#/definitions/EgovSearchModel'
    properties:
      clientReferenceId:
        type: "array"
        items:
          type: "string"
          description: "List of client reference IDs for searching entities."
        description: "A list of client reference IDs used in offline search operations."
  UserAction:
    allOf:
      - $ref: '#/definitions/EgovOfflineModel'
      - type: object
        properties:
          latitude:
            type: number
            format: double
            minimum: -90
            maximum: 90
          longitude:
            type: number
            format: double
            minimum: -180
            maximum: 180
          locationAccuracy:
            type: number
            format: double
            minimum: 0
          boundaryCode:
            type: string
          projectId:
            type: string
            minLength: 2
            maxLength: 64
          action:
            $ref: '#/definitions/UserActionEnum'
          beneficiaryTag:
            type: string
          resourceTag:
            type: string
        required:
          - projectId
          - latitude
          - longitude
          - locationAccuracy
          - boundaryCode
          - action

  UserActionBulkRequest:
    type: object
    properties:
      RequestInfo:
        $ref: '#/definitions/RequestInfo'
      UserActions:
        type: array
        items:
          $ref: '#/definitions/UserAction'
        minItems: 1
    required:
      - RequestInfo
      - UserActions

  UserActionBulkResponse:
    type: object
    properties:
      ResponseInfo:
        $ref: '#/definitions/ResponseInfo'
      TotalCount:
        type: integer
        default: 0
      UserActions:
        type: array
        items:
          $ref: '#/definitions/UserAction'
    required:
      - ResponseInfo
      - UserActions

  UserActionRequest:
    type: object
    properties:
      RequestInfo:
        $ref: '#/definitions/RequestInfo'
      UserAction:
        $ref: '#/definitions/UserAction'
    required:
      - RequestInfo
      - UserAction

  UserActionResponse:
    type: object
    properties:
      ResponseInfo:
        $ref: '#/definitions/ResponseInfo'
      UserAction:
        $ref: '#/definitions/UserAction'
    required:
      - ResponseInfo
      - UserAction

  UserActionSearchRequest:
    type: object
    properties:
      RequestInfo:
        $ref: '#/definitions/RequestInfo'
      UserAction:
        $ref: '#/definitions/UserActionSearch'

  UserActionSearch:
    allOf:
      - $ref: '#/definitions/EgovOfflineSearchModel'
    type: object
    properties:
      createdBy:
        type: string
      projectId:
        type: string
      boundaryCode:
        type: string
      beneficiaryTag:
        type: string
      resourceTag:
        type: string
  UserActionEnum:
    type: string
    enum:
      - CLOSED_HOUSEHOLD
      - LOCATION_CAPTURE
    description: Specify Task Action
  TaskStatus:
    type: string
    enum:
      - ADMINISTRATION_FAILED
      - ADMINISTRATION_SUCCESS
      - BENEFICIARY_REFUSED
      - CLOSED_HOUSEHOLD
      - DELIVERED
      - NOT_ADMINISTERED
    description: Specify Task Status
  UrlParams:
    type: "object"
    required:
      - "limit"
      - "offset"
      - "tenantId"
    properties:
      limit:
        type: "integer"
        format: "int32"
        minimum: 0
        maximum: 1000
        description: "The maximum number of records to be returned in the response."
      offset:
        type: "integer"
        format: "int32"
        minimum: 0
        description: "The offset from which records should be returned in the response."
      tenantId:
        type: "string"
        description: "The unique identifier for the tenant."
      lastChangedSince:
        type: "integer"
        format: "int64"
        description: "Epoch time representing the point in time since the last modification in the table."
      includeDeleted:
        type: "boolean"
        description: "Flag indicating whether soft deleted records should be included in search results."

