openapi: 3.0.1
info:
  title: Access Control APIs
  description: All APIs available from Access Control services.
  contact:
    name: eGov
    email: info@egovernments.org
  version: 1.0.1
servers:
- url: /
paths:
  /access/v1/actions/_authorize:
    post:
      tags:
        - Action
      summary: Authorize User
      description: |
        Authorize the user based on authorization request.
      operationId: authorizeUsingPOST
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthorizationRequestWrapper'
      responses:
        '200':
          description: OK
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  /access/v1/actions/_search:
    post:
      deprecated: true
      tags:
      - Action
      summary: Get the list of actions based on either roles or features.
      description: |
        Get the list of actions based on the input parameters.
      parameters:
      - name: roles
        in: query
        description: The list of role codes.
        style: form
        explode: false
        schema:
          type: array
          items:
            type: string
      - name: features
        in: query
        description: The list of feature id's.
        style: form
        explode: false
        schema:
          type: array
          items:
            type: integer
      requestBody:
        description: Request info for getting actions.
        content:
          '*/*':
            schema:
              $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/master/Common%20Services/common-contract.yaml#/components/schemas/RequestInfo'
        required: true
      responses:
        200:
          description: Successful response
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ActionResponse'
        400:
          description: Invalid input.
          content:
            '*/*':
              schema:
                $ref: "https://raw.githubusercontent.com/egovernments/DIGIT-Specs/master/Common%20Services/common-contract.yaml#/components/schemas/ErrorRes"
      x-codegen-request-body-name: requestInfo
  /access/v1/actions/_create:
    post:
      deprecated: true
      tags:
      - Action
      summary: Create a new action.
      description: |
        To create new action(s) in the system. An action entry is required for each and every path to authenticate the access based on the assigned role of an user.
      requestBody:
        description: Details for the new Action(s) entry + RequestInfo meta data.
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/ActionRequest'
        required: true
      responses:
        200:
          description: Action(s) created sucessfully
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ActionResponse'
        400:
          description: Action(s) creation failed
          content:
            '*/*':
              schema:
                $ref: "https://raw.githubusercontent.com/egovernments/DIGIT-Specs/master/Common%20Services/common-contract.yaml#/components/schemas/ErrorRes"
      x-codegen-request-body-name: actionRequest
  /access/v1/actions/_update:
    put:
      deprecated: true
      tags:
      - Action
      summary: Update existing action(s).
      description: "To update the existing action(s) in the system. \n"
      requestBody:
        description: Details for the Action(s) entry with new values + RequestInfo
          meta data.
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/ActionRequest'
        required: true
      responses:
        200:
          description: Update action(s) successful
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ActionResponse'
        400:
          description: Update action(s) failed
          content:
            '*/*':
              schema:
                $ref: "https://raw.githubusercontent.com/egovernments/DIGIT-Specs/master/Common%20Services/common-contract.yaml#/components/schemas/ErrorRes"
      x-codegen-request-body-name: actionRequest
  /access/v1/actions/mdms/_get:
    post:
      tags:
        - Action
      summary: getAllMDMSActions
      operationId: getAllMDMSActionsUsingPOST
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ActionRequest'
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found    
  /access/v1/actions/_validate:
    post:
      deprecated: true
      tags:
      - Action
      summary: Validate a particular action for a given tenant and roles of the tenant
      description: |
        Validate a particular action for a given tenant and roles of the tenant.
      requestBody:
        description: Request info for getting actions.
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/ValidateActionReq'
        required: true
      responses:
        200:
          description: Successful response without any content
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ValidateActionRes'
        400:
          description: Invalid input.
          content:
            '*/*':
              schema:
                $ref: "https://raw.githubusercontent.com/egovernments/DIGIT-Specs/master/Common%20Services/common-contract.yaml#/components/schemas/ErrorRes"
      x-codegen-request-body-name: ValidateActionReq
  /access/v1/roles/_search:
    post:
      deprecated: true
      tags:
      - Role
      summary: Get the list of roles based on role codes.
      description: |
        Get the list of roles based on role codes in the input parameters.
      parameters:
      - name: code
        in: query
        description: The list of comma separated codes to filter Roles against. No
          providing any would end up in all Roles as there is nothing to filter against
        style: form
        explode: false
        schema:
          type: array
          items:
            type: string
      requestBody:
        description: Request info for getting actions.
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/RolesReq'
        required: true
      responses:
        200:
          description: Successful response
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/RoleResponse'
        400:
          description: Invalid input.
          content:
            '*/*':
              schema:
                $ref: "https://raw.githubusercontent.com/egovernments/DIGIT-Specs/master/Common%20Services/common-contract.yaml#/components/schemas/ErrorRes"
      x-codegen-request-body-name: rolesReq
  /access/v1/roles/_create:
    post:
      deprecated: true
      tags:
      - Role
      summary: Create a new role.
      description: |
        To create new Role(s) in the system.
      requestBody:
        description: Details for the new role(s) + RequestInfo meta data.
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/RoleRequest'
        required: true
      responses:
        200:
          description: Role(s) created sucessfully
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/RoleResponse'
        400:
          description: Role(s) creation failed
          content:
            '*/*':
              schema:
                $ref: "https://raw.githubusercontent.com/egovernments/DIGIT-Specs/master/Common%20Services/common-contract.yaml#/components/schemas/ErrorRes"
      x-codegen-request-body-name: roleRequest
  /access/v1/roles/_update:
    put:
      deprecated: true
      tags:
      - Role
      summary: Update existing role(s).
      description: "To update the existing role(s) in the system. \n"
      requestBody:
        description: Details for the Role(s) entry with new values + RequestInfo meta
          data.
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/RoleRequest'
        required: true
      responses:
        200:
          description: Update role(s) successful
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/RoleResponse'
        400:
          description: Update role(s) failed
          content:
            '*/*':
              schema:
                $ref: "https://raw.githubusercontent.com/egovernments/DIGIT-Specs/master/Common%20Services/common-contract.yaml#/components/schemas/ErrorRes"
      x-codegen-request-body-name: roleRequest
  /access/v1/role-actions/_create:
    post:
      deprecated: true
      tags:
      - Role-Action
      summary: Create mapping for role and action(s).
      description: |
        Create mapping for role and action(s).
      requestBody:
        description: Details for the Role and Action(s) mapping + RequestInfo meta
          data.
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/RoleActionsRequest'
        required: true
      responses:
        200:
          description: Role - Action(s) mapping created sucessfully
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/RoleActionsResponse'
        400:
          description: Role - Action(s) mapping failed
          content:
            '*/*':
              schema:
                $ref: "https://raw.githubusercontent.com/egovernments/DIGIT-Specs/master/Common%20Services/common-contract.yaml#/components/schemas/ErrorRes"
      x-codegen-request-body-name: roleActionsRequest
components:
  schemas:
    Action:
      required:
      - name
      - tenantId
      type: object
      properties:
        id:
          type: integer
          description: Unique identifier of the Action.
          format: int64
        name:
          maxLength: 100
          minLength: 2
          type: string
          description: The Name of the Action.
        queryParams:
          maxLength: 100
          minLength: 5
          type: string
          description: The Name of the Action.
        url:
          maxLength: 100
          minLength: 10
          type: string
          description: The string url for the action.
        parentModule:
          type: integer
          description: Unique identifier of the Parent.
          format: int64
        orderNumber:
          type: integer
          description: Defines order for actions.
          format: int64
        displayName:
          maxLength: 100
          minLength: 2
          type: string
          description: The Name which is used for displaying.
        enabled:
          type: boolean
          description: True if the action is required and False if the action is not
            required.
        createdBy:
          type: integer
          description: Id of the user who created the record.
          format: int64
        createdDate:
          type: string
          description: Date on which the role master data was added into the system.
          format: date
        lastModifiedBy:
          type: integer
          description: Id of the user who last modified the record.
          format: int64
        lastModifiedDate:
          type: string
          description: Date on which the role master data was last modified.
          format: date
        tenantId:
          type: string
          description: Unique Identifier of the tenant, Like AP, AP.Kurnool etc.
        serviceCode:
          type: integer
          description: Defines service code.
          format: int64
    ActionRequest:
      required:
      - actions
      - requestInfo
      type: object
      properties:
        requestInfo:
          $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/master/Common%20Services/common-contract.yaml#/components/schemas/RequestInfo'
        actions:
          type: array
          items:
            $ref: '#/components/schemas/Action'
        actionMaster:
          type: string
          description: action master 
        enabled:
          type: boolean
          description: if enabled or not
        featureIds:
          type: array
          description: unique id for feature
          items: 
            type: integer
          format: int64
        leftIcon:
          type: string
          description: left icon
        navigationURL:
          type: string
          description: url for navigating
        rightIcon:
          type: string  
          description: right icon
        roleCodes:
          type: array
          description: codes specifying role 
          items: 
            type: string
        tenantId:
          minLength: 50
          type: string
          description: Unique Identifier of the tenant, Like AP, AP.Kurnool etc.        
    ActionResponse:
      type: object
      properties:
        responseInfo:
          $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/master/Common%20Services/common-contract.yaml#/components/schemas/ResponseInfo'
        actions:
          type: array
          items:
            $ref: '#/components/schemas/Action'      
    ActionValidation:
      required:
      - allowed
      type: object
      properties:
        allowed:
          type: string
          enum:
          - "TRUE"
          - "FALSE"        
    AuthorizationRequest:
      title: AuthorizationRequest
      required:
        - roles
        - tenantIds
        - uri
      type: object
      properties:
        roles:
          uniqueItems: true
          type: array
          minimum: 1
          items:
            $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/master/Common%20Services/common-contract.yaml#/components/schemas/Role'
        tenantIds:
          uniqueItems: true
          type: array
          minimum: 1
          description: Unique Identifier of the tenant, Like AP, AP.Kurnool etc.
          items:
            type: string
        uri:
          type: string
          description: sequence of characters that distinguishes one resource from another
    AuthorizationRequestWrapper:
      title: AuthorizationRequestWrapper
      type: object
      properties:
        AuthorizationRequest:
          $ref: '#/components/schemas/AuthorizationRequest'
        RequestInfo:
          $ref: "https://raw.githubusercontent.com/egovernments/DIGIT-Specs/master/Common%20Services/common-contract.yaml#/components/schemas/RequestInfo"      
    RoleAction:
      type: object
      properties:
        roleCode:
          type: string
          description: The Role Code which is mapped for the action.
        actionId:
          type: integer
          description: The Id of the Action which is mapped to the role.
          format: int64
        tenantId:
          type: string
          description: Unique Identifier of the tenant to which the role action mapping
            is done.      
    RoleRequest:
      required:
      - requestInfo
      - roles
      type: object
      properties:
        requestInfo:
          $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/master/Common%20Services/common-contract.yaml#/components/schemas/RequestInfo'
        roles:
          type: array
          items:
            $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/master/Common%20Services/common-contract.yaml#/components/schemas/Role'
    RoleActionsRequest:
      required:
      - actions
      - role
      - tenantId
      type: object
      properties:
        requestInfo:
          $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/master/Common%20Services/common-contract.yaml#/components/schemas/RequestInfo'
        role:
          $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/master/Common%20Services/common-contract.yaml#/components/schemas/Role'
        actions:
          type: array
          items:
            $ref: '#/components/schemas/Action'
        tenantId:
          type: string
          description: Unique Identifier of the tenant, Like AP, AP.Kurnool etc.
    RoleActionsResponse:
      type: object
      properties:
        responseInfo:
          $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/master/Common%20Services/common-contract.yaml#/components/schemas/ResponseInfo'
        roleActions:
          type: array
          items:
            $ref: '#/components/schemas/RoleAction'        
    RoleResponse:
      type: object
      properties:
        responseInfo:
          $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/master/Common%20Services/common-contract.yaml#/components/schemas/ResponseInfo'
        roles:
          type: array
          items:
            $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/master/Common%20Services/common-contract.yaml#/components/schemas/Role'
    RolesReq:
      type: object
      properties:
        RequestInfo:
          $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/master/Common%20Services/common-contract.yaml#/components/schemas/RequestInfo'        
    TenantRole:
      required:
      - roles
      - tenantId
      type: object
      properties:
        tenantId:
          type: string
          description: tenantid for the tenant
        roles:
          type: array
          description: Roles assigned for a particular tenant - array of role codes/names
          items:
            $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/master/Common%20Services/common-contract.yaml#/components/schemas/Role'
      description: User role carries the tenant related role information for the user.
        A user can have multiple roles per tenant based on the need of the tenant.
        A user may also have multiple roles for multiple tenants.  
    ValidateAction:
      required:
      - actionUrl
      - tenantRole
      type: object
      properties:
        tenantRole:
          $ref: '#/components/schemas/TenantRole'
        actionUrl:
          type: string
          description: Url of the action to be validated for given tenant
    ValidateActionReq:
      type: object
      properties:
        requestInfo:
          $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/master/Common%20Services/common-contract.yaml#/components/schemas/RequestInfo'
        validateAction:
          $ref: '#/components/schemas/ValidateAction'
    ValidateActionRes:
      type: object
      properties:
        responseInfo:
          $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/master/Common%20Services/common-contract.yaml#/components/schemas/ResponseInfo'
        actionValidation:
          $ref: '#/components/schemas/ActionValidation'

    
