---
openapi: 3.0.3
info:
  title: Document Uploader Service
  description: API specs for document uploader service
  termsOfService: urn:tos
  contact: {}
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0
  version: '1.0'
servers:
  - url: https://dev.digit.org
tags:
  - name: Document Uploader
paths:
  "/egov-document-uploader/egov-du/document/_create":
    post:
      tags:
        - Document Uploader
      summary: Create document
      description: Creates document and returns response
      operationId: createUsingPOST
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/DocumentRequest"
      responses:
        '200':
          description: Document(s) created successfully
          content:
            "*/*":
              schema:
                "$ref": "#/components/schemas/DocumentResponse"
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  "/egov-document-uploader/egov-du/document/_delete":
    post:
      tags:
        - Document Uploader
      summary: Delete document and returns response
      description: deletes document 
      operationId: deleteUsingPOST
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/DocumentRequest"
      responses:
        '200':
          description: Document(s) deleted successfully
          content:
            "*/*":
              schema:
                $ref: >-
                  https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-1-1.yml#/definitions/ResponseInfo
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  "/egov-document-uploader/egov-du/document/_search":
    post:
      tags:
        - Document Uploader
      summary: Search Document
      description: Searches document(s) using search criteria 
      operationId: searchUsingPOST
      parameters:
        - name: category
          in: query
          description: category of document
          required: false
          style: form
          schema:
            type: string
        - name: name
          in: query
          description: name on document
          required: false
          style: form
          schema:
            type: string
        - name: postedBy
          in: query
          description: name of entity who posted the document
          required: false
          style: form
          schema:
            type: string
        - name: tenantIds
          in: query
          description:  List of Unique ids for tenant
          required: false
          style: pipeDelimited
          schema:
            type: array
            items:
              type: string
        - name: uuid
          in: query
          description: "System Generated User id of the authenticated user."
          required: false
          style: form
          schema:
            type: string
        - name: fromDate
          in: query
          description: Transaction date, here search will happen as Transaction date is greater or equal to given fromDate
          required: false
          style: form
          schema:
            type: integer
        - name: toDate
          in: query
          description: Transaction date, here search will happen as Transaction date is lesser or equal to given toDate.
          required: false
          style: form
          schema:
            type: integer
        - name: viewDeletedDocuments
          in: query
          description: view deleted documents
          required: false
          style: form
          schema:
            type: boolean
        - name: offset
          in: query
          required: false
          style: form
          schema: 
            type: integer
        - name: limit
          in: query
          required: false
          style: form
          schema: 
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/RequestInfoWrapper"
      responses:
        '200':
          description: Search successful
          content:
            "*/*":
              schema:
                "$ref": "#/components/schemas/DocumentResponse"
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  "/egov-document-uploader/egov-du/document/_count":
    post:
      tags:
        - Document Uploader
      summary: Count Document
      description: Counts document(s) using search criteria 
      operationId: countUsingPOST
      parameters:
        - name: category
          in: query
          description: category of document
          required: false
          style: form
          schema:
            type: string
        - name: name
          in: query
          description: name on document
          required: false
          style: form
          schema:
            type: string
        - name: postedBy
          in: query
          description: name of entity who posted the document
          required: false
          style: form
          schema:
            type: string
        - name: tenantIds
          in: query
          description:  List of Unique ids for tenant
          required: false
          style: pipeDelimited
          schema:
            type: array
            items:
              type: string
        - name: uuid
          in: query
          description: "System Generated User id of the authenticated user."
          required: false
          style: form
          schema:
            type: string
        - name: fromDate
          in: query
          description: Transaction date, here search will happen as Transaction date is greater or equal to given fromDate
          required: false
          style: form
          schema:
            type: integer
        - name: toDate
          in: query
          description: Transaction date, here search will happen as Transaction date is lesser or equal to given toDate.
          required: false
          style: form
          schema:
            type: integer
        - name: viewDeletedDocuments
          in: query
          description: view deleted documents
          required: false
          style: form
          schema:
            type: boolean
        - name: offset
          in: query
          required: false
          style: form
          schema: 
            type: integer
        - name: limit
          in: query
          required: false
          style: form
          schema: 
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/RequestInfoWrapper"
      responses:
        '200':
          description: Count successful
          content:
            "*/*":
              schema:
                "$ref": "#/components/schemas/CountResponse"
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found      
  "/egov-document-uploader/egov-du/document/_update":
    post:
      tags:
        - Document Uploader
      summary: Update Document
      description: Updates document(s) 
      operationId: updateUsingPOST
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/DocumentRequest"
      responses:
        '200':
          description: Document update successful
          content:
            "*/*":
              schema:
                "$ref": "#/components/schemas/DocumentResponse"
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
components:
  schemas:
    DocumentEntity:
      title: DocumentEntity
      required:
        - tenantIds
      type: object
      properties:
        active:
          type: boolean
        auditDetails:
          "$ref": "https://raw.githubusercontent.com/egovernments/DIGIT-Specs/master/Common%20Services/common-contract.yaml#/components/schemas/AuditDetails"
        category:
          type: string
        description:
          maxLength: 140
          minLength: 0
          type: string
        documentLink:
          type: string
        fileSize:
          type: integer
          format: int64
        fileType: 
          type: string
        filestoreId:
          type: string
        name:
          type: string
        postedBy:
          type: string
        tenantId:
          type: string
        tenantIds:
          type: array
          items:
            type: string
        uuid:
          type: string
    DocumentRequest:
      title: DocumentRequest
      type: object
      properties:
        DocumentEntity:
          "$ref": "#/components/schemas/DocumentEntity"
        RequestInfo:
          $ref: >-
            https://raw.githubusercontent.com/egovernments/DIGIT-Specs/master/Common%20Services/common-contract.yaml#/components/schemas/RequestInfo
    DocumentResponse:
      title: DocumentResponse
      type: object
      properties:
        Documents:
          type: array
          items:
            "$ref": "#/components/schemas/DocumentEntity"
        ResponseInfo:
          $ref: >-
            https://raw.githubusercontent.com/egovernments/DIGIT-Specs/master/Common%20Services/common-contract.yaml#/components/schemas/ResponseInfo
    CountResponse:
      title: CountResponse
      type: object
      properties:
        ResponseInfo:
          $ref: >-
            https://raw.githubusercontent.com/egovernments/DIGIT-Specs/master/Common%20Services/common-contract.yaml#/components/schemas/ResponseInfo
        count:
          type: integer
    RequestInfoWrapper:
      title: RequestInfoWrapper
      type: object
      properties:
        RequestInfo:
          $ref: >-
            https://raw.githubusercontent.com/egovernments/DIGIT-Specs/master/Common%20Services/common-contract.yaml#/components/schemas/RequestInfo
