openapi: 3.0.1
info:
  title: Indexer service Api Documentation
  description: APIs available to initiate index jobs
  termsOfService: urn:tos
  contact:
    name: Abhishek Jain
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0
  version: 1.1.0
servers:
- url: /egov-indexer/index-operations
tags:
- name: egov-indexer service
paths:
  /index-operations/_legacyindex:
    post:
      tags:
      - egov-indexer service
      summary: This endpoint is used to start legacy index job to reindex records
        from DB. The data is fetched from DB by calling api mentioned in request in
        batches. The is useful when some record is present in DB but missing on index.
      description: Initiate legacy index job to index data from DB fetched by calling
        some api
      operationId: legacyIndexDataUsingPOST
      requestBody:
        description: legacyIndexRequest
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LegacyIndexRequest'
        required: true
      responses:
        200:
          description: Success response is calculated tax.
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/LegacyIndexResponse'
        401:
          description: Unauthorized
          content: {}
        403:
          description: Forbidden
          content: {}
        404:
          description: Not Found
          content: {}
      x-codegen-request-body-name: legacyIndexRequest
  /index-operations/_reindex:
    post:
      tags:
      - egov-indexer service
      summary: This endpoint is used to start indexing job to reindex records from
        one index to another index.
      description: Reindex data from one index to another
      operationId: reIndexDataUsingPOST
      requestBody:
        description: reindexRequest
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReindexRequest'
        required: true
      responses:
        200:
          description: Success response is calculated tax.
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ReindexResponse'
        401:
          description: Unauthorized
          content: {}
        403:
          description: Forbidden
          content: {}
        404:
          description: Not Found
          content: {}
      x-codegen-request-body-name: reindexRequest
  /index-operations/{key}/_index:
    post:
      tags:
      - egov-indexer service
      summary: This endpoint is used to index one record on a index. The information
        to pick correct config is provided with the data to be indexed.
      description: Index request to index one record on an index
      operationId: produceIndexJsonUsingPOST
      parameters:
      - name: key
        in: path
        description: key
        required: true
        schema:
          type: string
      requestBody:
        description: indexJson
        content:
          application/json:
            schema:
              type: object
            example:
                {
                  "service": {
                  "tenantId": "pb.amritsar",
                  "serviceCode": "NoStreetlight",
                  "description": "",
                  "additionalDetail": {},
                  "source": "web",
                  "address": {
                    "city": "Amritsar",
                    "district": "Amritsar",
                    "region": "Amritsar",
                    "state": "Panjab",
                    "pincode": "143001",
                    "locality": {
                      "code": "SUN04",
                      "name": "Ajit Nagar"
                        },
                    "geoLocation": {}
                    }
                  },
                  "workflow": {
                    "action": "APPLY"
                      }
                }  
        required: true
      responses:
        200:
          description: OK
          content:
            '*/*':
              schema:
                type: object
                example:
                  {
                  "service": {
                  "tenantId": "pb.amritsar",
                  "serviceCode": "NoStreetlight",
                  "description": "",
                  "additionalDetail": {},
                  "source": "web",
                  "address": {
                    "city": "Amritsar",
                    "district": "Amritsar",
                    "region": "Amritsar",
                    "state": "Panjab",
                    "pincode": "143001",
                    "locality": {
                      "code": "SUN04",
                      "name": "Ajit Nagar"
                        },
                    "geoLocation": {}
                    }
                  },
                  "workflow": {
                    "action": "APPLY"
                      }
                }  
        201:
          description: Created
          content: {}
        401:
          description: Unauthorized
          content: {}
        403:
          description: Forbidden
          content: {}
        404:
          description: Not Found
          content: {}
      x-codegen-request-body-name: indexJson
components:
  schemas:
    ReindexResponse:
      type: object
      properties:
        ResponseInfo:
          $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/master/Common%20Services/common-contract.yaml#/components/schemas/ResponseInfo'
        url:
          type: string
          description: url to access the particular file belong to the tag.
        totalRecordsToBeIndexed:
          type: number
          description: number of total records to be indexed
        estimatedTime:
          type: string
          description: estimate time
        message:
          type: string
          description: message
        jobId:
          type: string
          description: job id 
    LegacyIndexResponse:
      type: object
      properties:
        ResponseInfo:
          $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/master/Common%20Services/common-contract.yaml#/components/schemas/ResponseInfo'
        url:
          type: string
          description: url to access the particular file belong to the tag.
        message:
          type: string
          description: message
        jobId:
          type: string
          description: job id
    ReindexRequest:
      required:
        - RequestInfo
        - index
        - reindexTopic
        - tenantId
        - type
      type: object
      properties:
        RequestInfo:
          $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/master/Common%20Services/common-contract.yaml#/components/schemas/RequestInfo'
        batchSize:
          type: integer
          format: int32
          description: batch size
        index:
          type: string
          description: index
        jobId:
          type: string
          description: job id
        reindexTopic:
          type: string
          description: reindex topic
        startTime:
          type: integer
          description: start time 
          format: int64
        tenantId:
          type: string
          description: "Unique id for a tenant." 
        totalRecords:
          type: integer
          format: int32
          description: total number of records
        type:
          type: string
    APIDetails:
      type: object
      properties:
        customQueryParam:
          type: string
        paginationDetails:
          $ref: '#/components/schemas/PaginationDetails'
        request:
          description: Request details of API(s)
          type: object
          properties: {}
        responseJsonPath:
          description: Response json path for API(s)
          type: string
        tenantIdForOpenSearch:
          description: Unique tenant id for open search
          type: string
        uri:
          description: URI character sequence that identifies a logical abstract
          type: string
    LegacyIndexRequest:
      type: object
      properties:
        RequestInfo:
          $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/master/Common%20Services/common-contract.yaml#/components/schemas/RequestInfo'
        apiDetails:
          $ref: '#/components/schemas/APIDetails'
        jobId:
          description: Job id 
          type: string
        legacyIndexTopic:
          description: Topic of legacy index
          type: string
        startTime:
          description: Start time
          type: integer
          format: int64
        tenantId:
          description: Unique id for a tenant
          type: string
        totalRecords:
          description: Total number of records 
          type: integer
          format: int32
    PaginationDetails:
      type: object
      properties:
        maxPageSize:
          description: Maximum page size
          type: integer
          format: int32
        offsetKey:
          description: Offset key
          type: string
        sizeKey:
          description: Size key
          type: string
        startingOffset:
          type: integer
          format: int32
        maxRecords:
          type: integer
          format: int32  
