openapi: 3.0.1
info:
  title: Master Data Management Service
  description: APIs available to get the master data for perticuler tenant and module
    master.
  contact:
    name: Abhishek Jain
  version: 1.0.0
servers:
- url: /
paths:
  /egov-mdms-service/v1/_search:
    post:
      tags:
      - mdms-controller
      summary: Get list of masters for a particular module and tenantId.
      description: Get list of masters for a perticulare module and tenantId.
      requestBody:
        description: Details of module and master which need to be search using MDMS
          .
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/MdmsCriteriaReq'
        required: true
      responses:
        201:
          description: Designation created sucessfully.
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/MdmsResponse'
        400:
          description: Invalid input.
          content:
            '*/*':
              schema:
                $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/service-contracts/Common%20Services/common-contract.yaml#/components/schemas/ErrorRes'
      x-codegen-request-body-name: MdmsCriteriaReq
  /egov-mdms-service/v1/_get:
    post:
      tags:
      - mdms-controller
      summary: search
      operationId: searchUsingPOST
      parameters:
      - name: moduleName
        in: query
        description: moduleName
        required: true
        style: form
        schema:
          type: string
      - name: masterName
        in: query
        description: masterName
        required: true
        style: form
        schema:
          type: string
      - name: filter
        in: query
        description: filter
        required: false
        style: form
        schema:
          type: string
      - name: tenantId
        in: query
        description: tenantId
        required: true
        style: form
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "https://raw.githubusercontent.com/egovernments/DIGIT-Specs/service-contracts/Common%20Services/common-contract.yaml#/components/schemas/RequestInfo"
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                type: object
        '400':
          description: Invalid input.
          content:
            '*/*':
              schema:
                $ref: "https://raw.githubusercontent.com/egovernments/DIGIT-Specs/master/Common%20Services/common-contract.yaml#/components/schemas/ErrorRes"
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
components:
  schemas:
    MdmsCriteriaReq:
      type: object
      properties:
        RequestInfo:
          $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/service-contracts/Common%20Services/common-contract.yaml#/components/schemas/RequestInfo'
        MdmsCriteria:
          $ref: '#/components/schemas/MdmsCriteria'
    MdmsCriteria:
      required:
      - moduleDetails
      - tenantId
      type: object
      properties:
        tenantId:
          maxLength: 100
          minLength: 1
          type: string
          description: Unique id for for a tenant.
        moduleDetails:
          type: array
          items:
            $ref: '#/components/schemas/ModuleDetail'
    ModuleDetail:
      required:
      - masterDetails
      - moduleName
      type: object
      properties:
        moduleName:
          maxLength: 100
          minLength: 1
          type: string
          description: Name of the module for which master are required.
        masterDetails:
          type: array
          items:
            $ref: '#/components/schemas/MasterDetail'
    MasterDetail:
      required:
      - name
      type: object
      properties:
        name:
          maxLength: 100
          minLength: 1
          type: string
          description: Unique id for for a tenant.
        filter:
          maxLength: 500
          minLength: 1
          type: string
          description: Pass JsonPath predicate to get ther filtered data for a master.
    MdmsResponse:
      type: object
      properties:
        ResponseInfo:
          $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/service-contracts/Common%20Services/common-contract.yaml#/components/schemas/ResponseInfo'
        MdmsRes: 
          type: object
          properties: 
            requestedModule: 
              type: object
              properties: 
                requestedMaster: 
                  type: array
                  items: 
                    type: string
