openapi: 3.0.1
info:
  title: Egov otp service
  description: Egov-otp service APIs - contains create , validate and search end point
  contact:
    name: eGov
    email: info@egovernments.org
  version: 1.1.0
servers:
- url: /egov-otp/
paths:
  /otp/v1/_create:
    post:
      tags:
      - OTPConfig
      summary: create OTP Configuration entry
      description: create OTP Configuration this API is internaly call from v1/_send
        end point, this  end point present in user-otp service no need of explicity
        call
      requestBody:
        description: required parameters have to be populated
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/OtpRequest'
        required: true
      responses:
        200:
          description: Request acknowledged sucessfully
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/OtpResponse'
        400:
          description: Request failed
          content:
            '*/*':
              schema:
                $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/master/Common%20Services/common-contract.yaml#/components/schemas/ErrorRes'
      x-codegen-request-body-name: OTPConfig
  /otp/v1/_validate:
    post:
      tags:
      - OTPConfig
      summary: validate OTP Configuration entry
      description: validate OTP Configuration this end point is validate the otp respect
        to mobilenumber
      requestBody:
        description: required parameters have to be populated
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/OtpValidateRequest'
        required: true
      responses:
        200:
          description: Request acknowledged sucessfully
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/OtpResponse'
        400:
          description: Request failed
          content:
            '*/*':
              schema:
                $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/master/Common%20Services/common-contract.yaml#/components/schemas/ErrorRes'
      x-codegen-request-body-name: OTPConfig
  /otp/v1/_search:
    post:
      tags:
      - OTPConfig
      summary: search OTP Configuration entry using uuid
      description: search the mobile number and otp using uuid ,uuid nothing but otp
        reference number
      requestBody:
        description: required parameters have to be populated
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/OtpRequest'
        required: true
      responses:
        200:
          description: Request acknowledged sucessfully
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/OtpResponse'
        400:
          description: Request failed
          content:
            '*/*':
              schema:
                $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/master/Common%20Services/common-contract.yaml#/components/schemas/ErrorRes'
      x-codegen-request-body-name: OTPConfig
components:
  schemas:
    Otp:
      required:
      - identity
      - tenantId
      type: object
      properties:
        otp:
          maxLength: 128
          type: string
          description: this is the five digit otp number ,this is mandatory in validate
            end point should pass otp value in  /otp/v1/_validate end point, in other
            end point it is read only
        uuid:
          maxLength: 36
          type: string
          description: this is otp reference id, this is mandatory in search end point
            (/otp/v1/_search), and in other end point it is read only.
        identity:
          maxLength: 100
          type: string
          description: identity is  username or mobile number. this is  mandatory
            field in create and validate end point end point is(/otp/v1/_create, and
            /otp/v1/_validat) and optional field in /otp/v1/_search end point
        tenantId:
          maxLength: 256
          type: string
          description: Unique Identifier of the tenantId to which user primarily belongs
            and it is mandatory field in all the end points shoiuld pass this value
        isValidationSuccessful:
          type: string
          description: it return true or false  this is optional or read only property
            in all end point,
    OtpRequest:
      required:
      - otp
      type: object
      properties:
        otp:
          $ref: '#/components/schemas/Otp'
    OtpValidateRequest:
      required:
      - RequestInfo
      - otp
      type: object
      properties:
        RequestInfo:
          $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/master/Common%20Services/common-contract.yaml#/components/schemas/RequestInfo'
        otp:
          $ref: '#/components/schemas/Otp'      
    OtpResponse:
      type: object
      properties:
        ResponseInfo:
          $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/master/Common%20Services/common-contract.yaml#/components/schemas/ResponseInfo'
        otp:
          $ref: '#/components/schemas/Otp'
x-common-path: https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml
x-api-id: org.egov.egov-otp
