openapi: 3.0.1
info:
  title: eGov Payment Gateway Service.
  description: |
    This module acts as a liaison between eGov apps and external payment gateways. It facilitates payments, refunds and look up of transactions' status.
  contact:
    name: Egovernments Foundation
    email: contact@egovernments.org
  version: 1.0.0
servers:
- url: /egov-pg-service
paths:
  "/pg-service/gateway/v1/_search":
    post:
      description: |
        Returns the current status of a payment-gateway in our systems
      tags:
      - transactions-api-controller
      summary: transactionsV1AvailableGatewaysPost
      operationId: transactionsV1AvailableGatewaysPostUsingPOST
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                uniqueItems: true
                type: array
                items:
                  type: string
        '400':
          description: Invalid input.
          content:
            '*/*':
              schema:
                $ref: "https://raw.githubusercontent.com/egovernments/DIGIT-Specs/master/Common%20Services/common-contract.yaml#/components/schemas/ErrorRes"
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  "/pg-service/transaction/v1/_create":
    post:
      description: Initiates a new payment transaction, on successful validation, a redirect is issued to the payment gateway.
      tags:
      - transactions-api-controller
      summary: transactionsV1CreatePost
      operationId: transactionsV1CreatePostUsingPOST
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/TransactionRequest"
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                "$ref": "#/components/schemas/TransactionCreateResponse"
        '400':
          description: Invalid input.
          content:
            '*/*':
              schema:
                $ref: "https://raw.githubusercontent.com/egovernments/DIGIT-Specs/master/Common%20Services/common-contract.yaml#/components/schemas/ErrorRes"
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  "/pg-service/transaction/v1/_search":
    post:
      description: |
        Returns the current status of a payment in our systems.
      tags:
      - transactions-api-controller
      summary: transactionsV1SearchPost
      operationId: transactionsV1SearchPostUsingPOST
      parameters:
      - name: billId
        in: query
        description: Unique module based ID for which the transaction is being initiated, if billId is used, module should be included.
        required: false
        style: form
        schema:
          type: string
      - name: consumerCode
        in: query
        description: A unique identification for a billing entity.  
        required: false
        style: form
        schema:
          type: string
      - name: receipt
        in: query
        description: Receipt ID generated for this payment
        required: false
        style: form
        schema:
          type: string
      - name: tenantId
        in: query
        description: Unique id for a tenant.
        required: false
        style: form
        schema:
          type: string
      - name: txnId
        in: query
        description: Current id of the transaction
        required: false
        style: form
        schema:
          type: string
      - name: txnStatus
        in: query
        required: false
        style: form
        schema:
          type: string
          enum:
          - FAILURE
          - PENDING
          - SUCCESS
      - name: userUuid
        in: query
        description: User ID of the user as registered in user service, for whom the transaction was carried out.
        required: false
        style: form
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/RequestInfoWrapper"
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                "$ref": "#/components/schemas/TransactionResponse"
        '400':
          description: Invalid input.
          content:
            '*/*':
              schema:
                $ref: "https://raw.githubusercontent.com/egovernments/DIGIT-Specs/master/Common%20Services/common-contract.yaml#/components/schemas/ErrorRes"
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  "/pg-service/transaction/v1/_update":
    post:
      tags:
      - transactions-api-controller
      summary: transactionsV1UpdatePost
      operationId: transactionsV1UpdatePostUsingPOST
      parameters:
      - name: params
        in: query
        description: params
        required: true
        style: deepObject
        explode: true
        schema:
          type: object
          additionalProperties:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/RequestInfoWrapper"
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                "$ref": "#/components/schemas/TransactionResponse"
        '400':
          description: Invalid input.
          content:
            '*/*':
              schema:
                $ref: "https://raw.githubusercontent.com/egovernments/DIGIT-Specs/master/Common%20Services/common-contract.yaml#/components/schemas/ErrorRes"
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
components:
  schemas:
    Transaction:
      required:
      - billId
      - callbackUrl
      - gateway
      - productInfo
      - tenantId
      - txnAmount
      - consumerCode
      - taxAndPayments
      - user
      type: object
      properties:
        tenantId:
          maxLength: 50
          minLength: 2
          type: string
          description: The unique identifier for Service - this is equivalent to jurisdiction_id
            in Open311. As the platform intends to be multi tenanted - this is always
            required
        txnAmount:
          minLength: 1
          type: string
          description: Transaction Amount, preferably rounded off to two decimal places
        billId:
          minLength: 1
          type: string
          description: Unique bill ID associated with the transaction
        module:
          minLength: 1
          type: string
          description: Module business code for which the transaction is being initiated,
            ex PT, WS, PGR etc
        consumerCode:
          minLength: 1
          maxLength: 128
          type: string
          description: Unique identifier for consumer code
        taxAndPayments:
          minLength: 1
          type: array
          items:
            $ref: '#/components/schemas/TaxAndPayment'
        productInfo:
          minLength: 1
          maxLength: 512
          type: string
          description: Brief description for which the transaction is being carried
            out.
        gateway:
          minLength: 2
          type: string
          description: Gateway to be used, from the available list, such as PAYTM,
            PHONEPE.
        callbackUrl:
          minLength: 2
          type: string
          description: URL to which control has to be redirected to from the gateway
        txnId:
          type: string
          description: Transaction ID of the payment, generated by the gateway service
          readOnly: true
        user:
          $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/master/Common%20Services/common-contract.yaml#/components/schemas/User'
        redirectUrl:
          type: string
          description: redirectUrl of the payment
          readOnly: true
        txnStatus:
          type: string
          description: Current status of the transaction
          readOnly: true
          enum:
          - SUCCESS
          - FAILURE
          - PENDING
        txnStatusMsg:
          type: string
          description: Brief status message for the transaction
          readOnly: true
        gatewayTxnId:
          type: string
          description: Transaction ID returned by the gateway, for reference
          readOnly: true
        gatewayPaymentMode:
          type: string
          description: Mode of payment used at the gateway
          readOnly: true
        gatewayStatusCode:
          type: string
          description: Payment Gateway Specific RAW status code
          readOnly: true
        gatewayStatusMsg:
          type: string
          description: Payment Gateway Specific RAW status message
          readOnly: true
        receipt:
          type: string
          description: Receipt ID generated for this payment
          readOnly: true
        auditDetails:
          $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/master/Common%20Services/common-contract.yaml#/components/schemas/AuditDetails'
        additionalDetails:
          type: object
      description: Details of the payment object.
    TransactionRequest:
      type: object
      properties:
        RequestInfo:
          $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/master/Common%20Services/common-contract.yaml#/components/schemas/RequestInfo'
        Transaction:
          $ref: '#/components/schemas/Transaction'
    TransactionCreateResponse:
      title: TransactionCreateResponse
      type: object
      properties:
        ResponseInfo:
          "$ref": "https://raw.githubusercontent.com/egovernments/DIGIT-Specs/master/Common%20Services/common-contract.yaml#/components/schemas/ResponseInfo"
        Transaction:
          "$ref": "#/components/schemas/Transaction"
    RequestInfoWrapper:
      type: object
      properties:
        requestInfo:
          $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/master/Common%20Services/common-contract.yaml#/components/schemas/RequestInfo'
      description: Wrapper for Request Info
    TransactionResponse:
      type: object
      properties:
        responseInfo:
          $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/master/Common%20Services/common-contract.yaml#/components/schemas/ResponseInfo'
        Transaction:
          type: array
          items:
            $ref: '#/components/schemas/Transaction'
      description: The payment seatch response object, representing the status of
        the payment
    TaxAndPayment:
      title: TaxAndPayment
      type: object
      properties:
        billId:
          type: string
        taxAmount:
          type: number
          format: double
        amountPaid:
          type: number
          format: double
x-common-path: https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml
