openapi: 3.0.1
info:
  title: Egov URL shortening service
  description: APIs available in egov-url-shortening to shorten urls and get original
    urls from shortened urls
  contact:
    name: Abhishek Jain
  version: 1.0.0
servers:
- url: /egov-url-shortening
paths:
  /shortener:
    post:
      tags:
      - egov-url-shortening service endpoints
      summary: shorten given url
      operationId: shortenUrlUsingPOST
      requestBody:
        description: shortenRequest
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ShortenRequest'
        required: true
      responses:
        200:
          description: shortened url returned
          content:
            '*/*':
              schema:
                type: string
        400:
          description: Invalid input
          content:
            '*/*':
              schema:
                $ref: 'https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/definitions/ErrorRes'
      x-codegen-request-body-name: shortenRequest
  /{id}:  
    get:
      tags:
      - egov-url-shortening service endpoints
      summary: redirects user to orignal url identified by id
      parameters:
      - name: id
        in: path
        description: The uniqueue id field to find original url
        required: true
        schema:
          type: string
      responses:
        200:
          description: user redirected to original url
          content: {}
        400:
          description: invalid input
          content:
            '*/*':
              schema:
                $ref: 'https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/definitions/ErrorRes'
components:
  schemas:
    ShortenRequest:
      type: object
      required: [url]
      properties:
        id:
          type: string
          description: request id 
        url:
          type: string
          description: url to be shortened
        validFrom:
          type: integer
          format: int64
        validTill:
          type: integer
          format: int64
